### ISSUE TITLE
Show as many characters as necessary for a string column

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#101]
How many characters do we need for uniqueness? Use the corresponding extent. If more than 15, require only 15 characters. Careful with the quote/ellipsis.

**Comment by kovla** [comment]
Why not let the user decide how many characters they deem necessary? You have `pillar.min_title_chars` that controls column title truncation, why not implement something similar for character column width? 

As an aside, the workaround I am currently using is to set the mentioned option to Inf, and use variable name that exceeds or equals the number of characters I need to be shown (e.g., ID____________). Of course, this workaround is the same as having the separate option for column width, only less convenient.

**Comment by krlmlr** [comment]
Adding more options means complicating the code and the tests, I'm trying to keep the options to a minimum. How many characters would you like to see for character columns?

**Comment by kovla** [comment]
@krlmlr There probably will be as many opinions about this as there are users. People have different needs, and it is a daunting task to anticipate them all based on a single standard, which I suspect you are trying to do. 

I can only speak for my own experience as data analyst (or data scientist, whatever you call it), and hope that it can to some extent apply to similar use cases. In regard to my work, the most critical thing I need from the tibble print method, is to quickly evaluate whether the last transformation I applied to a data set worked out as intended, based on the columns displayed. By quickly, I mean in a single glance. Any truncation that I cannot control is likely to get in the way of that, as it is going to obscure the view. If a column occupies too much space for the print method (which very rarely occurs in practice), I can easily deselect it to get a better view or to use `View()` to get a deeper look. With the current print method, I need to resort to `View()` or other manipulations (like using contrived variable names, e.g., `ID__________`) almost by default. From the usability standpoint, this is the reverse situation from the ideal one. 

I certainly follow you in the wish to keep the number of options to a minimum, but I think this particular issue definitely warrants a little extra complexity to accommodate the large number of scenarios people find themselves in. 

Perhaps this issue would benefit from a broader discussion. Stackoverflow comes to mind as a potential forum, given that many `tidyverse` users are already there; though I'm not sure if moderators will find the format of the question fitting. I am also curious about what Hadley thinks of the issue, he is typically very spot on with things concerning usability.

**Comment by AshesITR** [comment]
Most ID columns in my day to day needs are only useful if displayed completely. Even if they are „unique“ enough if truncated, I can‘t copy them to clipboard and filter for them if they are incomplete.

In fact, the only character columns I don‘t need completely displayed would be those that are too long for an entire console line and in that case they won‘t be useful for a glance anyway.

As for character limits, my longest ID is 18 chars, but I imagine some folks will work with GUIDs - far longer than 18 chars.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by randomgambit** [comment]
I agree with @kovla . Just let the user decide. In Pandas, one can set up that, and this is great. For instance, at the moment I am working with news headlines. So I need to see everything and I would use a large max_n. At other times, this is a waste of space.

**Comment by cstubben** [comment]
If you can't set this as an option, then please use at least 18 characters since I'd really like to see IDs like ENSMUSG00000021877 again and not ENSMUS…

**Comment by randomgambit** [comment]
@krlmlr hello there! I am still wondering how to see my 20 character news headline stored in a tibble. Is there a workaround right now?

Thanks!!!

**Comment by randomgambit** [comment]
@krlmlr can we just set up an option here? I mean, this is a pretty standard thing dont you think? thanks!

**Comment by davidchall** [comment]
Or how about an option to disable truncation?

**Comment by krlmlr** [comment]
We now support a `pillar.min_chars` option, it's a good stop gap until we have a better understanding of how to specify formatting with the vector.

**Comment by krlmlr** [comment]
Would you like to test-drive [`char()`](https://pillar.r-lib.org/dev/reference/char.html#examples), available in pillar 1.5.1.9002, to be released as pillar 1.6.0? After release, I'll reexport this the constructor from tibble too. See https://pillar.r-lib.org/dev/articles/numbers.html for a documentation stub.

**Comment by krlmlr** [comment]
Abbreviation to preserves uniqueness will be handled elsewhere.
