### ISSUE TITLE
Thousand separator with color (RELOADED)

### ISSUE THREAD

**Issue by randomgambit** [r-lib/pillar#103]
Hi there, 

following @krlmlr 's advice I am re-opening this issue. I have played a bit with the latest release, and I have to say that the current underlining is nice, but the original idea from @krlmlr and @hadley (gray coloring) is perhaps more efficient here.

Indeed, I have a HD screen and I found it very hard to see the the difference between numbers like `432058` (6 digits) and `3948340` (7 digits) because the extra digit `3` in the second number will be so close to the underline for `948` that its hard to notice its the beginning of another 3-digit block... which kind of defeats the purpose of it. 

Why dont you try the gray shading thing and see how people react? Maybe as an `option(tibble.coloring = 'gray')`

**Comment by hadley** [comment]
Background shading is too difficult in general because we don't know what colour the background of the console is.

**Comment by randomgambit** [comment]
@hadley lets assume its white perhaps, cant you get the background color settings from Rstudio directly?

**Comment by krlmlr** [comment]
I forgot this would be solved by theming (#82), too. Just need to keep in mind to allow configuring the thousand separator/highlighting.

**Comment by randomgambit** [comment]
![image](https://user-images.githubusercontent.com/8282510/36902156-7b79f962-1df7-11e8-8a86-0f7c6c302d21.png)
