### ISSUE TITLE
Is the decimal point for double values with no numbers after it necessary?

### ISSUE THREAD

**Issue by martj42** [r-lib/pillar#105]
This is what the printout looks like now:

![](https://i.imgur.com/Hn8djda.png)

I think that looks a bit silly and even confusing. No one would write down a number as `13.`, maybe `13.0` to match formatting with other values that do have decimal numbers. Though I think the best way to do it would be to just lose the point.

**Comment by iacobus42** [comment]
There has been somewhat extensive discussion about this and, my understanding, is that it is worse to say "13" when it could be "13.x" than to say "13." when it can only be "13". 

If you want to suppress the decimal, you can also tell R that the variable is an integer.

**Comment by martj42** [comment]
Surely calling a `13` `13.` isn't the best way of doing it. Irregardless of what the best way of shortening longer decimals is.

As for changing the variable to an integer - sure, but for whatever reason down the pipe the column was created as a double and changing everything across my code would be too annoying. For the sake of the example, pretend half of the numbers have a `.5` behind them.

**Comment by huftis** [comment]
I was the one who originally [proposed the period for double values](https://github.com/r-lib/pillar/issues/40#issuecomment-360056414). But I agree that the solution actually implemented is both silly and confusing.

The idea was that the period could be used to indicate non-integer values *when the value was displayed in truncated form*. A missing period would then indicate a real integer (i.e. the fractional part would be 0). So `13` would indicate that the number was exactly 13, while `13.` would indicate that there was a (small) fractional part, e.g. the number was 3.0000000000678, but the fractional part was not displayed. But that’s not way it is currently implemented (see the on-going discussion in #40).

**Comment by WillemSleegers** [comment]
Just wanna leave my opinion and say I, too, find it silly and particularly confusing.
