### ISSUE TITLE
x10^14 seems to be mis-represented?

### ISSUE THREAD

**Issue by mattfidler** [r-lib/pillar#106]
![image](https://user-images.githubusercontent.com/514778/38347695-93d520d8-3862-11e8-96d8-49f0f8ba39a5.png)

I think it should be super-script as well.

**Comment by mattfidler** [comment]
Indeed it is the same as cli

```R
> cli::symbol$sup_4
[1] "4"
```
Which is not correct.

However, for 3 it is correct.  Therefore, indeed this is a issue in cli, not pillar.
```R
> cli::symbol$sup_3
[1] "³"
```

**Comment by mattfidler** [comment]
However, emacs indeed supports superscript 4.  You can insert it with the command `ucs-insert` which shows that I have font support, since it displays it.  Should I open an issue in the `cli` page?

**Comment by mattfidler** [comment]
Sorry for the delayed response.

**Comment by krlmlr** [comment]
Thanks, this is strange. What does `"\u2074" == "4"` give?

**Comment by mattfidler** [comment]
I agree.

`"\u2074" == "4"` is `FALSE`

**Comment by mattfidler** [comment]
I think to fix it I will have to browse through the R source code and see where this character is handled.  

I must say that UTF isn't techically supported through emacs/ESS on windows where I am working:

https://github.com/emacs-ess/ESS/issues/492

**Comment by mattfidler** [comment]
In theory, if R was working the way it does for all the rest of the unicode characeters, it should produce `"<U+2074>"` which would allow it to be displayed in emacs, so to me this is an issue in the R code base.

**Comment by krlmlr** [comment]
Could be a locale setting, too. What's `locale` (in the shell) or `Sys.getlocale()` on your system?

**Comment by mattfidler** [comment]
```
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> 
```

**Comment by mattfidler** [comment]
On windows `locale` isn't in the environment or a command.

**Comment by mattfidler** [comment]
I turned of the UTF parsing in emacs and found:
```
> "\u2074"
[1] "4"
> "\u00b3"
[1] "³"
> 
```

**Comment by mattfidler** [comment]
Still think this is a R/locale specific issue.

**Comment by krlmlr** [comment]
What do you get in RStudio or in RGui?

**Comment by mattfidler** [comment]
Rstudio gives the correct results.

![image](https://user-images.githubusercontent.com/514778/38873692-fc23b704-421b-11e8-9935-ac80f22c4fb7.png)

Rgui does not display the font and gives a box:

![image](https://user-images.githubusercontent.com/514778/38873758-1f62877c-421c-11e8-9392-a899acfb7692.png)

Rterm also seems to give the correct result

![image](https://user-images.githubusercontent.com/514778/38874010-b25e7004-421c-11e8-95e0-264b0ddf3df4.png)

I will have to look into this some more;  However I now doubt it is your issue or R's issue.

**Comment by mattfidler** [comment]
Actually on R-term "\u00b3" gives "3".  This confuses me even more because in theory emacs uses Rterm

```
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
```

**Comment by krlmlr** [comment]
I have no idea how RStudio achieves the ⁴ (the ³ is present in windows-1252, that's less surprising). Still I don't think we can do anything about it in *pillar*.

**Comment by mattfidler** [comment]
I agree.
