### ISSUE TITLE
Installation issue on windows 10

### ISSUE THREAD

**Issue by JVerstry** [r-lib/pillar#112]
Hi, I am facing a strange issue while trying to install pillar on Windows 10 from Visual Studio 2017. It only happens with the pillar package. I have described it here: https://stackoverflow.com/questions/50191556/install-packagespillar-fails-on-windows-10. I don't know whether it is specific to R or not, but I thought I would report here.
If anyone has a solution or workaround, that would be great. Thanks!

**Comment by krlmlr** [comment]
I answered on StackOverflow.
