### ISSUE TITLE
problem to implement new data type

### ISSUE THREAD

**Issue by aguerodev** [r-lib/pillar#116]
library(tibble)

#' @export
interval <- function(.min = NA_real_, .max =  NA_real_) {
  as_interval(list(min = .min, max = .max ))
}

#' @export
as_interval <- function(x) {
  structure(x, class = "interval")
}

#' @export
c.interval <- function(x, ...) {
  as_interval(NextMethod())
}

#' @export
`[[.interval` <- function(x, ...) {
  as_interval(NextMethod())
}

#' @export
format.interval <- function(x, ...) {
  min <- x$min
  max <- x$max
  ret <- paste0("[",min,",",max,"]")
  format(ret, justify = "right")
}

#' @export
print.interval <- function(x, ...) {
  cat(format(x), sep = "\n")
  invisible(x)
}

#' @importFrom pillar type_sum
#' @export
type_sum.interval <- function(x) {
  "interval"
}

#' @importFrom pillar pillar_shaft
#' @export
pillar_shaft.interval<- function(x, ...) {
  out <- format(x)
  out[is.na(x)] <- NA
  pillar::new_pillar_shaft_simple(out, align = "right")
}

x <- tibble(age = interval(18,56))
x
x[1,]

I am trying to implement a new class but the subsetting does not work correctly on the other hand the table says to have two observations when it should have only one.

Thank you in advance for the help, sorry if it is a question of something simple to solve.

**Comment by krlmlr** [comment]
Thanks. The data layout currently will not work with *dplyr*, which requires "simple" vectors with one vector element per items. You need to wrap complex data types in a list, as e.g. the *sf* package does.

For the special case of two real values, you can extend the `complex` data type as shown in the vignette.

Please test your data type independently of *pillar*. (In the current implementation, `` `[.interval`()`` looks suspicious, but I recommend reworking the data layout for reasons described above.)

**Comment by aguerodev** [comment]
some other package that is integrated with tibble to use that code as a reference

**Comment by krlmlr** [comment]
Can you please rephrase?

**Comment by hadley** [comment]
Closing, since the S3 class is not vectorised correctly.
