### ISSUE TITLE
Class label in tibble does not correspond to actual class for class array 

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/pillar#121]
Essentially transferred from https://github.com/tidyverse/tibble/issues/432.

I don't know how the `<dbl>`  and friends label are derived from data, but I thought they were class labels (and not type labels). If this is the case, the following seems unexpected:
`timetrend` has class `"array"` but the printing says `<dbl>`.
``` r
library(tibble)
mtcars <- as_tibble(mtcars)
m <- mgcv::gam(cyl ~s(mpg), data = mtcars)
fitted <- mgcv::predict.gam(m, newdata = mtcars, type = "link") 

mtcars[, "timetrend"] <- fitted
class(mtcars$timetrend)
#> [1] "array"
mtcars
#> # A tibble: 32 x 12
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>  * <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # ... with 22 more rows, and 1 more variable: timetrend <dbl>
```

Created on 2018-07-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

It was consensus in https://github.com/tidyverse/tibble/issues/432 that the class label should correspond to the actual class.

**Comment by hadley** [comment]
That presumes that `fitted` has a class, but it does not. What you are seeing part of the class that S3 implies when given a class-less object:

``` r
library(tibble)
mtcars <- as_tibble(mtcars)
m <- mgcv::gam(cyl ~s(mpg), data = mtcars)
fitted <- mgcv::predict.gam(m, newdata = mtcars, type = "link") 

attr(fitted, "class")
#> NULL

sloop::s3_class(fitted)
#> [1] "array"   "double"  "numeric"
```

The convention that I am working from in vctrs is that 1d arrays should be treated identically to vectors. I think this makes the most sense, rather than creating a new type of object that is subtly different (but not in any important way) from a common existing type.

**Comment by krlmlr** [comment]
Should 1d array columns print (or behave) any differently from regular vector columns?

**Comment by hadley** [comment]
No.

**Comment by krlmlr** [comment]
With #153, we now have:

``` r
pillar::pillar(array(1:3, dim = 3))
#> <int>
#>     1
#>     2
#>     3

pillar::pillar(array(1:3, dim = c(3, 1)))
#> <int[,1]>
#>         1
#>         2
#>         3
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

To be super consistent, we would format the type in the first case as `<int[]>`, but {vctrs} doesn't distinguish internally between 1-dim arrays and vectors: https://github.com/r-lib/vctrs/blob/master/R/dim.R . I think there's nothing we can or should do here, except making sure that 1-d arrays are properly supported in tibbles.
