### ISSUE TITLE
Move type_sum to rlang and reexport

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#124]
@lionel-: Now _rlang_ has its own version of `type_sum()`, perhaps the generic should be defined there? What do we need to do in _rlang_ for this to happen? The main challenge might be testing various combinations of _rlang_ and _pillar_.?

**Comment by hadley** [comment]
I think pillar could probably depend on a putative `vec_type_sum()`

**Comment by hadley** [comment]
Replaced by #134
