### ISSUE TITLE
Misleading decimal point for rounded values

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#126]
``` r
pillar::pillar(567.89)
#> <dbl>
#>  568.
```

> Created on 2018-08-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

@hadley: Would it work to use a different symbol instead of the decimal point here, to indicate that the true value is lower?

**Comment by hadley** [comment]
I think that would be confusing as there is no common symbol used for that purpose

**Comment by krlmlr** [comment]
What should we do? Get rid of the dot, or document the behavior?

**Comment by hadley** [comment]
Just document, I think

**Comment by krlmlr** [comment]
Still thinking about a good venue. The "Get started" vignette in {tibble}?

**Comment by hadley** [comment]
How about we just make a new vignette that discusses tibble formatting?

**Comment by krlmlr** [comment]
Now documented in https://pillar.r-lib.org/dev/articles/digits.html .
