### ISSUE TITLE
Import fansi in DESCRIPTION but not in NAMESPACE

### ISSUE THREAD

**Issue by brodieG** [r-lib/pillar#128]
Maybe the latter is not necessary, although I always assumed it was, and WRE appears to suggest it should be:

> Packages implicitly import the base namespace. Variables exported from other packages with namespaces need to be imported explicitly using the directives import and importFrom. The import directive imports all exported variables from the specified package(s).

I'm actually rather surprised that R CMD check doesn't complain.

Adding something like:

```
#' @importFrom fansi substr_ctl strip_sgr
```
in `zzz.R` or elsewhere should suffice.

I tried to do this via a PR, but it looks like you have a rather non-standard setup with r-lib pkgapi so I wasn't able to rebuild docs and I don't have time right now to wrangle with that.  This also explains why `fansi` namespace was not loaded on loading `pillar` which I was confused about yesterday.

**Comment by krlmlr** [comment]
Thanks. All functions from _fansi_ are called with `fansi::`, the package is loaded upon first usage. Why is it important to load _fansi_ when _pillar_ is loaded?

**Comment by brodieG** [comment]
I just read it to be a requirement from WRE.  Obviously CRAN doesn't seem to check for that so perhaps it is not a strict requirement.

**Comment by krlmlr** [comment]
Later it reads:

> If a package only needs a few objects from another package it can use a fully qualified variable reference in the code instead of a formal import. ...

**Comment by brodieG** [comment]
Great, thanks, sorry for the bother.

**Comment by krlmlr** [comment]
You're welcome. The downside is, as you noticed, that _fansi_ doesn't show up in the session info right after loading _pillar_, only after running the relevant code. There must be performance overhead too (with using `::` instead of importing), but the more explicit code seems worth it.
