### ISSUE TITLE
pillar_shaft.character() should have optional quote argument

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#130]
The default should be `TRUE` to indicate that quotes should be automatically where needed. You'd use `quote = FALSE` in the first pass of your `pillar_shaft()` method implementation so you can take advantage of an existing format method:

```R
pillar_shaft.percent <- function(x) {
  pillar::pillar_shaft(format(x), quote = FALSE)
}
```

**Comment by krlmlr** [comment]
Resolved with the current implementation of `pillar_shaft.default()` . Classes that only want to use `format()` don't need to implement a `pillar_shaft()` method.
