### ISSUE TITLE
obj_sum.list should call generic

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#137]
The current code means that there's no way to customise the display of objects inside a list-col.

Should be:

```
obj_sum.list <- function(x) {
  map_chr(x, obj_sum)
}
```

**Comment by hadley** [comment]
I think this should probably actual be some variant of `format()` — we only need to handle base classes (mostly lists) specially because `format()` doesn't always do the right thing.

**Comment by krlmlr** [comment]
Thinking again, looks like the current implementation isn't that far off: `obj_sum.default()` calls `type_sum()` and `size_sum()`, this provides opportunities to tweak the output.?

**Comment by krlmlr** [comment]
Do we still need to change anything here if {vctrs} gets a `pillar_shaft.vctrs_list_of()` method (https://github.com/r-lib/vctrs/pull/317)?

**Comment by hadley** [comment]
Yeah, I'd say we can probably ignore.

**Comment by hadley** [comment]
I do think we need to figure this out, particularly as we use list columns of custom objects more frequently.

**Comment by hadley** [comment]
`obj_sum.POSIXlt()` looks wrong too:

``` r
x <- as.POSIXlt(Sys.Date() + 1:10)
pillar::obj_sum(x)
#>  [1] "POSIXlt" "POSIXlt" "POSIXlt" "POSIXlt" "POSIXlt" "POSIXlt" "POSIXlt"
#>  [8] "POSIXlt" "POSIXlt" "POSIXlt"
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Maybe the problem is that `pillar_shaft.list()` should do the looping, not `obj_sum()`:

```R
pillar_shaft.list <- function(x, ...) {
  out <- paste0("<", map_chr(x, obj_sum), ">")

  width <- get_max_extent(out)

  new_pillar_shaft_simple(style_list(out), width = width, align = "left", min_width = min(width, 3L))
}
```

That way `obj_sum()` has a clear contract to always return an object of length 1.

**Comment by krlmlr** [comment]
While we're at it: I think the following looks odd (and has been mentioned elsewhere too):

``` r
library(pillar)

obj_sum(matrix(1:4, ncol = 2))
#> [1] "int[,2] [2 × 2]"
obj_sum(Titanic)
#> [1] "table [4 × 2 × 2 × 2]"
obj_sum(unclass(Titanic))
#> [1] "dbl[,2,2,2] [4 × 2 × 2 × 2]"
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(`Titanic` is an object of class `table`.)

Do we need a variant of `vec_ptype_abbr()` that omits the shape? Or should we only add the length here, and `table` also gets a shape in `vec_ptype_abbr()`?

CC @lionel-.

**Comment by krlmlr** [comment]
Shape weirdness discussed in #168.
