### ISSUE TITLE
Use one (nested) pillar for data frame and matrix columns

### ISSUE THREAD

**Issue by const-ae** [r-lib/pillar#142]
Hi, I was yesterday playing around with the [vctrs](https://github.com/r-lib/vctrs) package, creating a type for MCMC posterior samples, that internally is a matrix, but looks and behaves like a simple numeric vector. The idea behind it is to make handling those samples simpler (i.e. taking the difference of the runs etc.). 

This all working quite well, but unfortunately pillar seems to be ignoring the `format` function I wrote for the type, and displays the vctrs as the matrix it is internally:

``` r
library(vctrs)
library(tibble)

post <- function(x=matrix(, nrow=0, ncol=0)){
  if(is.vector(x)){
    x <- as.matrix(x)
  }
  stopifnot(is.matrix(x))
  
  new_vctr(c(x), nsamples=ncol(x), dim=c(nrow(x), ncol(x)), class="post")
}

as.matrix.post <- function(x, ...){
  matrix(vec_data(x), ncol=attr(x, "nsamples"))
}

format.post <- function(x, ...){
  rowMeans(as.matrix(x))
}
obj_print_footer.post <- function(x, ...) {
  cat("nsamples: ", attr(x, "nsamples"), "\n", sep = "")
}

`[.post` <- function(x, i, j, drop=FALSE){
  m <- as.matrix(x)[i,j,drop=drop]
  post(m)
}

vec_arith.post <- function(op, x, y) UseMethod("vec_arith.post", y)
vec_arith.post.post <- function(op, x, y){
  nsamples_x <- attr(x, "nsamples")
  nsamples_y <- attr(y, "nsamples")
  mx <- as.matrix(x)
  my <- as.matrix(y)
  res <- t(vapply(seq_len(vec_size(x)), function(idx){
    c(outer(mx[idx, ], my[idx, ], op))
  }, FUN.VALUE = rep(0.0, nsamples_x * nsamples_y)))
  post(res)
}

p1 <- post(rbind(rnorm(10, mean=1),
                 rnorm(10, mean=10),
                 rnorm(10, mean=-2),
                 rnorm(10, mean=4)))
p2 <- post(rbind(rnorm(3, mean=1),
                 rnorm(3, mean=-10),
                 rnorm(3, mean=0),
                 rnorm(3, mean=10)))

p1
#> <post[40]>
#> [1]  0.8163855  9.6762014 -1.5743212  4.1346032
#> nsamples: 10
p2
#> <post[12]>
#> [1]  0.7319972 -9.9491694  0.3368831  9.2285601
#> nsamples: 3
p1 + p2
#> <post[120]>
#> [1]  1.5483827 -0.2729679 -1.2374380 13.3631632
#> nsamples: 30

df <- tibble(abc=letters[1:4], p2)
as.data.frame(df)
#>   abc         p2
#> 1   a  0.7319972
#> 2   b -9.9491694
#> 3   c  0.3368831
#> 4   d  9.2285601
df
#> # A tibble: 4 x 2
#>   abc               p2[,1]               [,2]               [,3]
#>   <chr>             <post>             <post>             <post>
#> 1 a      0.172519602906773 0.0588098684335713    1.9646620956729
#> 2 b      -10.3594901450867  -9.71129156443163  -9.77672639449069
#> 3 c     -0.177959609558753   1.57355653495115 -0.384947503221933
#> 4 d        10.349987018383   10.4663913594914   6.86930179123215
```
<sup>Created on 2018-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I would prefer tibble/pillar to output my type the way the classical `data.frame` does, not spitting out the internal matrix. So I was wondering if there are any plans to handle such 2D vctr types specifically?

I also apologize in advance if this not the right place for this issue, but I thought that because the internal logic for [handling matrices](https://github.com/r-lib/pillar/blob/master/R/multi.R#L72) is in this package, this would be a good place to start.

**Comment by const-ae** [comment]
Thank you for the response. But are you sure that the this is a tibble issue? I think the problem is that the vector is identified as a matrix ([here](https://github.com/r-lib/pillar/pull/143/commits/0a33177dc683efb2b506441c18c9f568905c882f)) and thus the formatting is not ideal.

**Comment by krlmlr** [comment]
The reprex demonstrates that when using `pillar_shaft()` alone this problem doesn't occur. Pretty sure _tibble_ sees a matrix and decides to split.

**Comment by krlmlr** [comment]
Of course you're right:

``` r
library(vctrs)

post <- function(x = matrix(, nrow = 0, ncol = 0)) {
  if (is.vector(x)) {
    x <- as.matrix(x)
  }
  stopifnot(is.matrix(x))

  new_vctr(c(x), nsamples = ncol(x), dim = c(nrow(x), ncol(x)), class = "post")
}

as.matrix.post <- function(x, ...) {
  matrix(vec_data(x), ncol = attr(x, "nsamples"))
}

format.post <- function(x, ...) {
  rowMeans(as.matrix(x))
}
obj_print_footer.post <- function(x, ...) {
  cat("nsamples: ", attr(x, "nsamples"), "\n", sep = "")
}

`[.post` <- function(x, i, j, drop = FALSE) {
  m <- as.matrix(x)[i, j, drop = drop]
  post(m)
}

vec_arith.post <- function(op, x, y) UseMethod("vec_arith.post", y)
vec_arith.post.post <- function(op, x, y) {
  nsamples_x <- attr(x, "nsamples")
  nsamples_y <- attr(y, "nsamples")
  mx <- as.matrix(x)
  my <- as.matrix(y)
  res <- t(vapply(seq_len(vec_size(x)), function(idx) {
    c(outer(mx[idx, ], my[idx, ], op))
  }, FUN.VALUE = rep(0.0, nsamples_x * nsamples_y)))
  post(res)
}

p1 <- post(rbind(
  rnorm(10, mean = 1),
  rnorm(10, mean = 10),
  rnorm(10, mean = -2),
  rnorm(10, mean = 4)
))

pillar::colonnade(list(p1))
#>                [,1]              [,2]              [,3]              [,4]
#>          <S3: post>        <S3: post>        <S3: post>        <S3: post>
#> 1 0.325263452764748  2.35021366067693  1.07498895845799  2.21436040234289
#> 2  9.58679984853479  10.8822408190294  10.3289570474228  12.0277292065522
#> 3 -2.25769349323456 -1.95431796502964 -2.65018653726676 -1.63126769076285
#> 4  4.63032905287646  3.67629171256413  2.78824318790206  1.34135126735779
```

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
Looks like we need to make the following work better:

``` r
pillar::pillar(diag(3))
#> Registered S3 method overwritten by 'vctrs':
#>   method                   from 
#>   as.character.rlang_error rlang
#> <dbl[,3]>
#>         1
#>         0
#>         0
#>         0
#>         1
#>         0
#>         0
#>         0
#>         1

pillar::pillar(array(1:8, dim = c(2, 2, 2)))
#> Registered S3 method overwritten by 'vctrs':
#>   method                   from 
#>   as.character.rlang_error rlang
#> <int[,2,2]>
#>           1
#>           2
#>           3
#>           4
#>           5
#>           6
#>           7
#>           8
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I'd expect that in the first case the data is treated like a column, and an error in the second case.

@hadley: Do we support arrays with more than two dimensions in a tibble?

**Comment by krlmlr** [comment]
To implement this properly, we need something conceptually between a pillar and a colonnade. Maybe we can extend the concept of colonnades to support nested colonnades -- e.g. `colonnade()` could be a generic overridden only by matrix- and data-frame-like classes, and the default would forward to `pillar()` .

@const-ae: Could you please point me to the implementation of your column class?

**Comment by hadley** [comment]
Matrices aren't recursive in the same way that data frames are, so I think we could just have the pillar of a matrix be a single column.

**Comment by krlmlr** [comment]
Good point. I wonder if wrapping (for multi-tier output with `tibble.width > width`) is useful for hierarchical columns or matrices. Treating a matrix as a single pillar will make wrapping difficult. We'll need to gather more information if and how multi-tier output is used.

**Comment by const-ae** [comment]
> @const-ae: Could you please point me to the implementation of your column class?

Sorry, I am a little confused. Do you mean the function `pillar_shaft.post`? I am relying on the `pillar:::pillar_shaft.default()` method, which in turn calls my `format.post()` method:
```R
format.post <- function(x, ...) {
  rowMeans(as.matrix(x))
}
```

My original issue was that `colonnade()` internally uses a check `is.matrix()` ([here](https://github.com/r-lib/pillar/blob/4c35a0cef661eaadd9341d66a9bdfb0574383bd7/R/multi.R#L54)), which ignores the class and simply checks if `length(dim(x)) == 2` ([here](https://github.com/wch/r-source/blob/5ffefa197f4b644fd85730fc795be964726a738a/src/include/Rinlinedfuns.h#L895)), which is why `pillar_shaft` is not even called for my class.

But, I have the impression that you want to change the way 2D vectors are printed anyway, so I am not sure I can give much input into that topic.

**Comment by krlmlr** [comment]
Got you. I'll consider keeping matrices in a single pillar, this will help your use case.

**Comment by DavisVaughan** [comment]
I just hit the strange printing of arrays as 1d vectors. I also noticed that the row names shown depend on whether or not the array is the first element in the tibble.

``` r
library(tibble)

tbl <- tibble(y = 4:5, x = array(1:2, dim = c(2,2,2)))

tbl
#> # A tibble: 2 x 2
#>       y           x
#>   <int> <int[,2,2]>
#> 1     4           1
#> 2     5           2
#> 1     4           1
#> 2     5           2
#> 1     4           1
#> 2     5           2
#> 1     4           1
#> 2     5           2

# row id working incorrectly if array is up front because
# `length(array) = num elements`. Called from:
# pillar:::get_rowid_from_colonnade
tbl[c("x", "y")]
#> # A tibble: 2 x 2
#>             x     y
#>   <int[,2,2]> <int>
#> 1           1     4
#> 2           2     5
#> 3           1     4
#> 4           2     5
#> 5           1     4
#> 6           2     5
#> 7           1     4
#> 8           2     5

# underlying objects are still correct
tbl$x
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    1    1
#> [2,]    2    2
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]    1    1
#> [2,]    2    2

tbl$y
#> [1] 4 5
```

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
It's not a matrix, so it must be a vector... We need an update here before we submit tibble 3.0.0, I'll take a look.
