### ISSUE TITLE
To install from GitHub you need to install devtools

### ISSUE THREAD

**Issue by sanjay-singh3210** [r-lib/pillar#150]
To install from GitHub you need to install devtools
`install.packages("devtools")`

_Originally posted by @batpigandme in https://github.com/r-lib/pillar/issues/92#issuecomment-459538148_

Hi, I am getting following error message when I am trying to install devtools. I am using Win10. Can you suggest how to fix it?
-------------
> install.packages("devtools")
Installing package into ‘C:/Users/yagga/OneDrive/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘git2r’, ‘pkgbuild’, ‘pkgload’, ‘rcmdcheck’

  There are binary versions available but the source versions are later:
          binary source needs_compilation
git2r     0.21.0 0.24.0              TRUE
rcmdcheck  1.2.1  1.3.2             FALSE
devtools  1.13.5  2.0.1             FALSE

  Binaries will be installed
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘pkgload’
  These will not be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/git2r_0.21.0.zip'
Content type 'application/zip' length 3022652 bytes (2.9 MB)
downloaded 2.9 MB

package ‘git2r’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\yagga\AppData\Local\Temp\RtmpiGM0SV\downloaded_packages
installing the source packages ‘pkgbuild’, ‘rcmdcheck’, ‘devtools’

trying URL 'https://cran.rstudio.com/src/contrib/pkgbuild_1.0.2.tar.gz'
Content type 'application/x-gzip' length 25264 bytes (24 KB)
downloaded 24 KB

trying URL 'https://cran.rstudio.com/src/contrib/rcmdcheck_1.3.2.tar.gz'
Content type 'application/x-gzip' length 1408582 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/src/contrib/devtools_2.0.1.tar.gz'
Content type 'application/x-gzip' length 388953 bytes (379 KB)
downloaded 379 KB

* installing *source* package 'pkgbuild' ...
** package 'pkgbuild' successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'callr', details:
  call: loadNamespace(name)
  error: there is no package called 'debugme'
ERROR: lazy loading failed for package 'pkgbuild'
* removing 'C:/Users/yagga/OneDrive/Documents/R/win-library/3.3/pkgbuild'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.3.3/bin/x64/R" CMD INSTALL -l "C:\Users\yagga\OneDrive\Documents\R\win-library\3.3" C:\Users\yagga\AppData\Local\Temp\RtmpiGM0SV/downloaded_packages/pkgbuild_1.0.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘pkgbuild’ had non-zero exit status
ERROR: dependency 'pkgbuild' is not available for package 'rcmdcheck'
* removing 'C:/Users/yagga/OneDrive/Documents/R/win-library/3.3/rcmdcheck'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.3.3/bin/x64/R" CMD INSTALL -l "C:\Users\yagga\OneDrive\Documents\R\win-library\3.3" C:\Users\yagga\AppData\Local\Temp\RtmpiGM0SV/downloaded_packages/rcmdcheck_1.3.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘rcmdcheck’ had non-zero exit status
ERROR: dependencies 'pkgbuild', 'pkgload', 'rcmdcheck' are not available for package 'devtools'
* removing 'C:/Users/yagga/OneDrive/Documents/R/win-library/3.3/devtools'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.3.3/bin/x64/R" CMD INSTALL -l "C:\Users\yagga\OneDrive\Documents\R\win-library\3.3" C:\Users\yagga\AppData\Local\Temp\RtmpiGM0SV/downloaded_packages/devtools_2.0.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\yagga\AppData\Local\Temp\RtmpiGM0SV\downloaded_packages’
> library("devtools")
Error in library("devtools") : there is no package called ‘devtools’

**Comment by krlmlr** [comment]
Can you try:

```r
install.packages("devtools", type = "win.binary")
```

?

These questions, which are not immediately related to this package, are a better fit for https://community.rstudio.com. Can you please ask over there next time? (https://www.tidyverse.org/help/ contains tips that maximize your chances of getting a good answer.)

**Comment by sanjay-singh3210** [comment]
Hi @krlmlr Thanks! Based on this thread on R Community Page https://community.rstudio.com/t/specific-packages-seem-to-have-crashed-my-rstudio/21222 I have updated to R 3.5 and it has solved the issue. I wanted to use R 3.3.3 with SPSS 25 but that doesnt seem working . I am just posting it here so that it may help to someone facing similar issue in future. 
Reagrds
