### ISSUE TITLE
Soft-deprecation of type_sum()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#154]
`type_sum()` now forwards to `vec_ptype_abbr()`, but there are concerns regarding its deprecation:

- Is `vec_ptype_abbr()` stable (https://github.com/r-lib/pillar/issues/134#issuecomment-447648442)? Type descriptions to be shown in a word/sentence/paragraph are supposed to be new generics (https://github.com/r-lib/vctrs/issues/139#issuecomment-489082459), forwarding to existing `vec_ptype_abbr()` functions here.

- `type_sum()` also works for non-vector types, `vec_ptype_abbr()` does not. This isn't a huge problem, but still worth mentioning.

@hadley: Do we initiate soft-deprecation now? It seems safe -- it's only a message once per session, and also only for direct callers.

**Comment by hadley** [comment]
I think we should avoid soft-deprecating now, if we're going to soft-deprecate to something else in the near future.

**Comment by krlmlr** [comment]
One thing to keep in mind: Some packages might override `type_sum()` to return a classed object, which affects the display of the type in a pillar. See `?pillar_type_sum`.

**Comment by krlmlr** [comment]
We also should think about `obj_sum()` and `is_vector_s3()`.

**Comment by krlmlr** [comment]
Do we move it to vctrs, along with perhaps `obj_sum()` and a new `size_sum()` (#173)?

**Comment by krlmlr** [comment]
Let's keep the status quo for now.
