### ISSUE TITLE
`pillar_shaft.vctrs_list_of()` has no customization point

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pillar#173]
I was planning on creating a `vctrs_list_of` class where each element would be a tibble containing "notes" (i.e. errors and warnings) that happened during model tuning. I would like to be able to control the printing enough to have an end result like:

```r
# A tibble: 2 x 1
            x
  <list<tbl_notes>>
1       [1 W / 2 E]
2       [0 W / 3 E]
```

After looking at this issue https://github.com/r-lib/pillar/issues/137, I was hoping that `pillar_shaft.vctrs_list_of()` would help.

But the current implementation of `pillar_shaft.vctrs_list_of()` provides no customization points for me.

https://github.com/r-lib/pillar/blob/82370d73e9f5b96689454fab675087d0ef0993c9/R/vctrs.R#L18-L23

Is there any hope that we could go back and do what #137 suggests by calling `map(x, obj_sum)`? Then I could control `obj_sum.tbl_notes`

**Comment by krlmlr** [comment]
Now that this is implemented in vctrs, maybe we should discuss there?

The implementation here needs to vanish when the vctrs update hits CRAN.

**Comment by DavisVaughan** [comment]
What is implemented in vctrs?

**Comment by krlmlr** [comment]
I only saw https://github.com/r-lib/vctrs/pull/317/files#diff-775b2077c6dd77196f7d75e853496705R151 but it's gone since r-lib/vctrs#338. So the issue is good here. Hiding the last three comments.

**Comment by krlmlr** [comment]
Maybe `vctrs::list_of(1:3)` could be of class `c("vctrs_list_of_integer", "vctrs_list_of", "vctrs_vctr")`, similarly for other types/classes? This would allow you to fine-tune by implementing your own `pillar_shaft()` .

I don't mind tweaking the method either. We don't have output tests yet, this would be a good opportunity to add them.

**Comment by DavisVaughan** [comment]
> implementing your own pillar_shaft()

I can do that now I suppose. I could just make a `vctrs_list_of_tbl_notes` class myself using `new_list_of(class = "vctrs_list_of_tbl_notes")` and then make a `pillar_shaft()` method for that.

I suppose I ideally just wanted to implement the minimal amount of things possible, which would be a `obj_sum.tbl_notes` method

**Comment by krlmlr** [comment]
`pillar_shaft()` methods for vctrs live here.

I don't think we want to show `obj_sum()` inside a `list_of()`, because it consists of a `type_sum()` (which is already shown in the haeader) and a `size_sum()` (for which we don't have a generic yet). Should we add a `size_sum()` generic?

**Comment by DavisVaughan** [comment]
I think a `size_sum()` generic sounds useful

**Comment by krlmlr** [comment]
Do you think we can/should move them to vctrs? How?

**Comment by lionel-** [comment]
Maybe first implement `size_sum()` in pillar as an experimental generic?

**Comment by krlmlr** [comment]
Sure, let's do that.

**Comment by topepo** [comment]
Is this getting fixed/changed? I have tibbles with list columns. The elements of the lists are tibbles with extra classes and the default print method is not good: 

```r
> cell_models %>% select(result)
# A tibble: 6 x 1
  result          
  <list>          
1 <tibble [1 × 4]>
2 <tibble [1 × 4]>
3 <tibble [1 × 4]>
4 <tibble [1 × 4]>
5 <tibble [1 × 4]>
6 <tibble [1 × 4]>
```

This obscures the nature of the result since it looks like a simple tibble. 

I'd rather it be something like: 

```r
> cell_models %>% select(result)
# A tibble: 6 x 1
  result          
  <list>          
1 <tune>
2 <tune>
3 <resample>
4 <tune>
5 <tune>
6 <tune>
```

or similar. 

This looks to be related to #137. @hadley suggested [these functions](https://vctrs.r-lib.org/articles/pillar.html) but I don't think that is the solution since I have list columns.

**Comment by krlmlr** [comment]
@topepo: I'm fixing this, but your issue seems unrelated. Can you confirm that #238 describes the problem you're seeing, or open a new issue with a reprex? Hiding the last two messages here.

**Comment by DavisVaughan** [comment]
To possibly help with @topepo's problem, I have learned that he could do:

```r
library(pillar)
library(tibble)
#> Warning: package 'tibble' was built under R version 4.0.2
lst <- list(x = 1)
tbl <- new_tibble(lst, nrow = 1L)
result1 <- new_tibble(lst, nrow = 1L, class = "tune_result")
result2 <- new_tibble(lst, nrow = 1L, class = "resample_result")
type_sum.tune_result <- function(x) {
  "tune-result"
}
type_sum.resample_result <- function(x) {
  "resample-result"
}
col <- list(tbl, result1, result2)
tibble(col = col)
#> # A tibble: 3 x 1
#>   col                      
#>   <list>                   
#> 1 <tibble [1 × 1]>         
#> 2 <tune-result [1 × 1]>    
#> 3 <resample-result [1 × 1]>
# You can do the above with CRAN pillar
# With PR #239
size_sum.tune_result <- function(x) {
  ""
}
size_sum.resample_result <- function(x) {
  ""
}
tibble(col = col)
#> # A tibble: 3 x 1
#>   col              
#>   <list>           
#> 1 <tibble [1 × 1]> 
#> 2 <tune-result>    
#> 3 <resample-result>
```
