### ISSUE TITLE
Deprecate is_vector_s3()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#181]
in favor of `vec_is()`.

**Comment by krlmlr** [comment]
In the next major release.

**Comment by krlmlr** [comment]
Switch to warning in the next minor release.

**Comment by krlmlr** [comment]
Need dialr > 0.3.2 to get rid of it entirely.

**Comment by krlmlr** [comment]
@gorcha: Are you planning a dialr CRAN release any time soon?

**Comment by gorcha** [comment]
Hey @krlmlr, I didn't have one necessarily planned but I can do! I'll try and get an update submitted in the next day or so.

**Comment by krlmlr** [comment]
Thanks, that was quick!

**Comment by gorcha** [comment]
No worries! Wasn't far off a release anyway :slightly_smiling_face:
