### ISSUE TITLE
Consider exporting align() function?

### ISSUE THREAD

**Issue by davidchall** [r-lib/pillar#185]
I'm planning to use {pillar} to add pretty-printing support to a couple of {vctrs} classes (see https://github.com/davidchall/ipaddress/pull/27).

In doing so, I found the `pillar:::align()` function to be very helpful in aligning the individual components of the class around a common character (`/`). This is similar to how numeric vectors align around the decimal point.

Would you consider exporting this function in the next release of {pillar}? If not, would it be okay if I copy this function into my package? (I'd personally prefer the former, because this function requires a backported `strrep` function.)

https://github.com/r-lib/pillar/blob/e7e029152b3c4b905e986316a990e542141ce9fb/R/extent.R#L31-L43

**Comment by krlmlr** [comment]
I don't mind reexporting (we'd probably use `arg_match()`), happy to review a pull request. You can also copy if you like.

Would you like to add your class to https://github.com/krlmlr/awesome-vctrs#readme?

**Comment by davidchall** [comment]
Ah, good idea! I'll open a PR at awesome-vctrs shortly
