### ISSUE TITLE
'broken' label

### ISSUE THREAD

**Issue by davidread** [r-lib/pillar#196]
@krlmlr Do you happen to know why several non-current versions of pillar on conda get labelled 'broken' - e.g. [1.4.2](https://anaconda.org/conda-forge/r-pillar/files)? At our org, we snapshot our package versions in conda, so that we can reproduce our analysis code at a later date. However when a package gets labelled as broken then it won't install by default, and we have to guide users to try various workarounds.

**Comment by krlmlr** [comment]
I'm not using conda. It seems this is something the maintainer (?) of that package can define on Anaconda Cloud?
