### ISSUE TITLE
Heterogeneous list column customization

### ISSUE THREAD

**Issue by rundel** [r-lib/pillar#197]
I have a use case where I am constructing a tibble with a list column that contains a heterogenous collection of S3 class objects. Some of these objects are lists others are atomic vectors. I would like to be able to customize the printing of these objects within the tibble without having to go through the process of adding meta-classes and defining a `new_list_of` to wrap everything together.

My current approach is similar to the code below, I can add `type_sum` methods for each of my classes and get close to something workable, but for the atomic vector s3 class objects the [size] suffix seems unavoidable currently (See output for class B and C below). 

```
library(pillar)

A = structure(list(x=1, y=2), class="A")
B = structure(1:3, class="B")
C = structure(letters[1:3], class="C")

tibble::tibble(
  d = list(A,B,C)
)
#> # A tibble: 3 x 1
#>   d      
#>   <list> 
#> 1 <A>    
#> 2 <B [3]>
#> 3 <C [3]>

type_sum.A = function(x) {
  cli::style_bold("Class A")
}

type_sum.B = function(x) {
  cli::style_bold("Class B")
}

type_sum.C = function(x) {
  cli::style_bold("Class C")
}

tibble::tibble(
  d = list(A,B,C)
)
#> # A tibble: 3 x 1
#>   d            
#>   <list>       
#> 1 <Class A>    
#> 2 <Class B [3]>
#> 3 <Class C [3]>
```

There was some mention in #173 of a generic version of `size_sum` which would solve this I think. With that said, it would be nice if it were possible to also adjust things like the blurring and `<>` brackets without having to jump through all of the vctrs hoops.

**Comment by krlmlr** [comment]
Thanks. I don't have a good answer here. If values of `B` and `C` are vectors, what's wrong with showing their sizes? If they're not, their sizes will not be shown.

vctrs treats all subclasses of the atomic types as vectors. I'm not sure if this is subject to change; lists are treated as vectors when they explicitly inherit from the `"list"` class. You can however explicitly indicate that a type is not a vector, by having `vec_proxy()` return a non-vector type. Then it loses the size suffix; the downside is that vctrs won't treat this as vector altogether:

``` r
library(pillar)

A <- structure(list(x = 1, y = 2), class = "A")
B <- structure(1:3, class = "B")
C <- structure(letters[1:3], class = "C")

vec_proxy.B <- function(x) new.env(parent = emptyenv())

tibble::tibble(
  d = list(A, B, C)
)
#> # A tibble: 3 x 1
#>   d      
#>   <list> 
#> 1 <A>    
#> 2 <B>    
#> 3 <C [3]>
```

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rundel** [comment]
In my use case A, B, C are all containers but in some cases it is easier to keep them as atomic vectors and others as lists - for the sake of consistency it would be nice if they all printed the same way. Everything could be wrapped in a list but it seems like an unnecessary extra layer of complexity. 

I think the `vec_proxy` approach will work - it just feels a bit hacky (but then I think my complaint is with vctrs and not pillar).
