### ISSUE TITLE
properly print Surv objects

### ISSUE THREAD

**Issue by topepo** [r-lib/pillar#199]
Objects produced by `survival::Surv()` are matrices not vectors. They print nicely in data frames but not tibbles. Can we fix that? 

``` r
library(survival)
library(tibble)
options(width = 120)
lung$surv_obj <- Surv(lung$time, lung$status)

print(head(lung))
#>   inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss surv_obj
#> 1    3  306      2  74   1       1       90       100     1175      NA      306
#> 2    3  455      2  68   1       0       90        90     1225      15      455
#> 3    3 1010      1  56   1       0       90        90       NA      15    1010+
#> 4    5  210      2  57   1       1       90        60     1150      11      210
#> 5    1  883      2  60   1       0      100        90       NA       0      883
#> 6   12 1022      1  74   1       1       50        80      513       0    1022+

print(head(as_tibble(lung)))
#> # A tibble: 6 x 11
#>    inst  time status   age   sex ph.ecog ph.karno pat.karno meal.cal wt.loss surv_obj[,"time"] [,"status"]
#>   <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>    <dbl>     <dbl>    <dbl>   <dbl>             <dbl>       <dbl>
#> 1     3   306      2    74     1       1       90       100     1175      NA               306           1
#> 2     3   455      2    68     1       0       90        90     1225      15               455           1
#> 3     3  1010      1    56     1       0       90        90       NA      15              1010           0
#> 4     5   210      2    57     1       1       90        60     1150      11               210           1
#> 5     1   883      2    60     1       0      100        90       NA       0               883           1
#> 6    12  1022      1    74     1       1       50        80      513       0              1022           0
```

<sup>Created on 2020-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
This is how tibble prints matrices:

``` r
my_lung <- head(survival::lung[c("time", "status")])
surv <- survival::Surv(my_lung$time, my_lung$status)
dim(surv)
#> [1] 6 2
is.matrix(surv)
#> [1] TRUE
class(surv)
#> [1] "Surv"

tibble::tibble(m = matrix(1:6, ncol = 2))
#> # A tibble: 3 x 1
#>   m[,1]  [,2]
#>   <int> <int>
#> 1     1     4
#> 2     2     5
#> 3     3     6
tibble::tibble(m = matrix(1:6, ncol = 2, dimnames = list(NULL, c("x", "y"))))
#> # A tibble: 3 x 1
#>   m[,"x"] [,"y"]
#>     <int>  <int>
#> 1       1      4
#> 2       2      5
#> 3       3      6
```

<sup>Created on 2020-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Do we need to special-case for objects of class `"Surv"`? Or change the way matrices are printed in general?

**Comment by topepo** [comment]
I'd rather have a method specifically for `Surv` objects without revisiting how matrices are shown (above my pay grade).

**Comment by krlmlr** [comment]
I think the right way would be to implement `pillar_shaft.Surv()` in the survival package, this requires some noweb knowledge :-o.

This method can also live in any other package that imports vctrs and perhaps suggests survival. Can you think of a good candidate?

**Comment by krlmlr** [comment]
(Yeah, pillar is the obvious one, I'd rather avoid dumping methods for classes here. This case might be special though.)

**Comment by topepo** [comment]
It's highly unlikely that Terry would take extra package dependencies for `Surv`. Honestly, `pillar` is probably the best place for the method.  In an integral data structure to R and would be used quite a lot.

**Comment by krlmlr** [comment]
Surv2 output changed in the dev version of survival to include `:2`, do we need to worry about this?

https://github.com/r-lib/pillar/runs/1958070499?check_suite_focus=true#step:13:139

**Comment by krlmlr** [comment]
Fixed.
