### ISSUE TITLE
Re-licensing pillar

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#215]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/pillar/graphs/contributors). @davidchall, @statsmaths, would you permit us to re-license pillar with the MIT license? If so, please comment "I agree" below.

* [x] [@davidchall](https://github.com/r-lib/pillar/commits?author=davidchall)  
* [x] [@statsmaths](https://github.com/r-lib/pillar/commits?author=statsmaths)

**Comment by davidchall** [comment]
I agree

**Comment by statsmaths** [comment]
I agree
