### ISSUE TITLE
Idea on datetimes/timezones

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/pillar#25]
Following this idea from tidyverse/tibble#173 - guessing that this is the place now.

The idea in the original issue is to do something like:

```
#> # A tibble: 1 × 3
#>                 time1               time2               time3
#>                <dttm>           <dttm-02>           <dttm+11>
#> 1 2015-06-01 01:00:00 2015-06-01 01:00:00 2015-06-01 01:00:00
```

The non-DST offset is shown in the column header.

Given that you are now using color and font-weight as signifiers, could this be applied to datetimes?

The column header could be something like `<dttm+11+12>` then the `+11`, `+12`, and values could be colored/weighted accordingly.

**Comment by hadley** [comment]
I don't know of a good (even approximate) way of generating the UTC offset.  (Also need to remember that some time zones have partial hour offsets)

**Comment by krlmlr** [comment]
RcppCCTZ maybe?

**Comment by ijlyttle** [comment]
Assuming RcppCCTZ meets the needs, I think the partial-hour problem could be overcome by using something like:
 
```
<dttm-03:30/-02:30>
2015-06-01 01:00:00
```

which would _just_ fit. 

I think the "range" of the offsets offered could be limited to the date-times being considered in the given column. 

On the one hand, this would limit the printing of dual-offset headers to those cases where both offsets appear in the tibble. On the other hand, that would seem to make it harder to format consistently for normal and daylight-saving offsets.

**Comment by hadley** [comment]
And over long periods of time, I bet only two offsets is insufficient

**Comment by ijlyttle** [comment]
If I'm reading the conversation correctly it sounds like this feature, though potentially useful, has edge cases that make things sufficiently difficult so as to outweigh the benefits.

I'll close the issue in the hopes that I will be able to do some twiddling around myself.

If I come up with something worth talking about, I'll be happy to reopen and make a PR, even if only for the entertainment value ;)

If you (@hadley or @krlmlr) think this is worth keeping open, you'll not offend me by re-opening.

**Comment by krlmlr** [comment]
Happy to review a PR, but for now I'll focus on plugging the existing code into tibble.

**Comment by krlmlr** [comment]
I think we could just add the time zone verbatim: Date-times use 19 characters anyway, most time zone descriptors (known to my system) are 14 characters or shorter:

``` r
quantile(nchar(OlsonNames()))
#>   0%  25%  50%  75% 100% 
#>    2   12   14   17   32
```

This means using `<dt-...>` as column type will display the time zone in full for half of the time zones, and it will be abbreviated automatically (and occupy only 19 spaces) if too wide. Thoughts?

**Comment by hadley** [comment]
Olson names are probably amenable to human shortening - split in two pieces, manually abbreviate first and then call `abbreviate()` on the second?

**Comment by krlmlr** [comment]
@ijlyttle: Would you like to take a stab?

**Comment by ijlyttle** [comment]
I would like to - first, let me look and see to make sure I can get my level-of-understanding where it needs to be to contribute.

**Comment by ijlyttle** [comment]
I had a look, and I think I understand the idea - at it's core, we would want a function that would take an Olson string, then return an abbreviated string of no more than 14 characters.  Something like:

```r
#' Abbreviate an Olson timezone to 14 characters
abbreviate_olson <- function(x) {

}
```

Then, you could take returned string and embed it into `<dt-...>`, which would then be a maximum of 19 characters.

Alternatively, such a function could return all (max) 19 characters. 

I don't know if you will want this in its own function or not, but it will give me a place to start. 

Let me see what I can do here.

**Comment by hadley** [comment]
Yeah exactly - and a separate function would be fine.

**Comment by ijlyttle** [comment]
Just a heads-up that I don't think I can get to this until the end-of-the week (2017-09-16). I am eager to do it, but I don't want to be blocking things either.

**Comment by krlmlr** [comment]
No worries, that's fine.

**Comment by randomgambit** [comment]
hello there! I am just wondering, what about DST time changes? I mean, assume I print something between midnight and 5am on a DST day, the column  header will be wrong, right? Can you possibly print some additional stuff? Like an asterisk or something that indicates this is a DST day?

**Comment by ijlyttle** [comment]
As I understand it, the column header will refer to a time zone that is fixed to a geography, i.e. `"America/New_York"`, which will not change if it is DST (or not).

How to address the significance of values for which DST is in effect would be a separate question, IMHO.

**Comment by randomgambit** [comment]
huuuum the more I think about it, the more printing the offset seems dead wrong.... The header will be likely to be wrong whenever the data encompasses a DST switch - which is very likely. Most useful in my opinion would be to have the Olson name (America-NY) abbreviated if needed.

**Comment by krlmlr** [comment]
Closing, should be possible to implement with the help of https://github.com/tidyverse/tibble/pull/411 or a similar approach.
