### ISSUE TITLE
.onLoad failed in loadNamespace() for 'pillar'

### ISSUE THREAD

**Issue by richarddmorey** [r-lib/pillar#252]
I'm attempting to deploy a package to shinyapps.io, and I am getting an error that has to do with pillar and crayon. I'm following up with the RStudio folks but I wanted to ask here in case you've any insight.

Basic issue

When trying to deploy an Rmd file to shinyapps.io (https://github.com/richarddmorey/shinyapps_problem/blob/master/inst/Rmd/solve.Rmd), the installation of packages fails with this error:

```
# Error: .onLoad failed in loadNamespace() for 'pillar', details:
#   call: loadNamespace(name)
#   error: there is no package called ‘crayon’
# Execution halted
# ERROR: lazy loading failed for package ‘flexTeaching’
```

I've intentionally constructed `flexTeaching` package as a minimal package to show the problem. It is installed from here: https://github.com/richarddmorey/shinyapps_problem The only thing this package does is define a single (unexported) function:

```
#' @importFrom dplyr arrange `%>%` 
getAssignments = function(simple = FALSE){

  cars %>% 
    arrange(dist)

}
```

and so it has a dependency on dplyr, which depends on tibble, which depends on pillar, which depends on crayon. Apparently others have had this issue: https://community.rstudio.com/t/failed-to-deployapp-error-there-is-no-package-called-crayon/89921 (but no responses).

Complete reproducible code with inline comments showing the output (along with with sessioninfo, etc) can be found here: https://github.com/richarddmorey/shinyapps_problem/blob/master/inst/R/demo_code.R

The shiny app works fine on my system, so I suspect it is a problem with a botched build/install of pillar or crayon on shinyapps.io (which runs Ubuntu, I gather) but I don't know.

Any insight would be greatly appreciated.

**Comment by richarddmorey** [comment]
(This issue seems relevant: https://github.com/tidyverse/dplyr/issues/4641)

**Comment by krlmlr** [comment]
Sorry, this slipped through the cracks.

When deploying to shinyapps or RStudio Connect, sometimes it helps to have the packages managed by renv.

This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximize your chances of getting a good answer.)

**Comment by richarddmorey** [comment]
> sometimes it helps to have the packages managed by renv.

They are. As shown at https://github.com/richarddmorey/shinyapps_problem/blob/master/inst/R/demo_code.R, the status just before the error is `# * Successfully installed and loaded renv 0.12.5.` - this may or may not mean there's an issue with renv?

>This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? 

Yes, I linked to an identical issue on community.rstudio.com, but it was not answered. I've been back and forth with Rstudio shiny support as well, who have thus far considered it a "custom package" problem. But the stripped down package only does one thing!

> (You might want to read https://www.tidyverse.org/help/ first to maximize your chances of getting a good answer.)

The stripped down package plus https://github.com/richarddmorey/shinyapps_problem/blob/master/inst/R/demo_code.R are a reprex, as long as you can deploy to shinyapps (I've reproduced it across three OSs).

**Comment by krlmlr** [comment]
I'm sorry to hear that.

One thing to keep in mind with renv is to avoid deploying `.Rprofile`, `renv/` directory, and `renv.lock` . Can you confirm?

Ultimately this may be a problem with the packrat package that is used by Connect and shinyapps under the hood.

**Comment by richarddmorey** [comment]
> One thing to keep in mind with renv is to avoid deploying `.Rprofile`, `renv/` directory, and `renv.lock` . Can you confirm?

hmmm, as far as I can tell, I'm only deploying the one .Rmd file, not anything else (deploy command here: https://github.com/richarddmorey/shinyapps_problem/blob/d7b5cc0ca629e2adbf69ee60c3223b9c9c42e5d6/inst/R/demo_code.R#L70-L77); the issue arises after installing dependencies for the .Rmd file, which include dplyr.

(maybe I misunderstand what you mean)

**Comment by krlmlr** [comment]
Thanks. I'll try to deploy your example to see if I can replicate it.

**Comment by krlmlr** [comment]
I cloned https://github.com/richarddmorey/shinyapps_problem, but there seems to be no `renv.lock` . I'm having a hard time installing the flexTeaching package. Please advise.

**Comment by richarddmorey** [comment]
I just committed my lockfile (https://github.com/richarddmorey/shinyapps_problem/blob/master/renv.lock). Thanks for looking at this.

**Comment by krlmlr** [comment]
Thanks. Now I see, when rendering `solve.Rmd`:

```
Quitting from lines 10-14 (solve.Rmd) 
Error in loadNamespace(name) : there is no package called 'flexTeaching'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

**Comment by richarddmorey** [comment]
That's strange; did the package successfully install with devtools::install_github()? (https://github.com/richarddmorey/shinyapps_problem/blob/master/inst/R/demo_code.R ) I've replicated this across 3 OSs. The Rmd renders in each.

**Comment by krlmlr** [comment]
I didn't try that, I'd expect that the package is installed with `renv::restore()` .

**Comment by richarddmorey** [comment]
As far as I can tell the code in `demo_code.R` replicates the error (with the appropriate substitutions for shinyapps.io credentials). I tried it again last night and got the same error.

**Comment by krlmlr** [comment]
Thanks. I hadn't noticed that `demo_code.R` contains the whole log.

Here's what I think is happening:

- the code deploys everything to shinyapps.io, including `.Rprofile`
- shinyapps.io restores the project library
- the project starts, runs its `.Rprofile` and initializes an empty library with only renv installed
- crayon (and many other packages) are not available

A few suggestions:

- Do not deploy an renv-generated `.Rprofile`
- If you have renv, you should never need to manually install anything for deployment. Everything should be encoded in your `renv.lock`, so that your collaborators can run `renv::restore()` and have all the packages that you have

**Comment by richarddmorey** [comment]
Would the .Rprofile be deployed even when specifically only deploying the Rmd file? I would expect that no other files are included implicitly but I'm misunderstanding something about how the deployment works.

**Comment by krlmlr** [comment]
I'm not sure, I remember a dialog to choose files even when deploying a single `.Rmd` file.

Happy to give it another try with an `renv.lock` that installs all necessary packages.

**Comment by richarddmorey** [comment]
I have gotten back to this (sorry for the delay; I was kind of naively hoping that package updates would solve this). I've cleaned up my demo so that `renv` installs everything, including my test package. The demo code, with more recent log, in a branch of the repository: https://github.com/richarddmorey/shinyapps_problem/tree/test2

Steps to reproduce:

1. Download the branch code (zip file: https://github.com/richarddmorey/shinyapps_problem/archive/refs/heads/test2.zip)
2. Unzip, open the project
3. Open `r/demo_code.R` and run it, making appropriate changes to the username for the `rsconnect` calls

The code will attempt to deploy the `solve.Rmd` file. 

I have tried this on my Windows 10 and macOS systems with the same result. You can see the log of a macOS run here:
https://github.com/richarddmorey/shinyapps_problem/blob/test2/R/demo_code.R
 
The same problem is still:

```
[2021-07-07T11:10:33.858207433+0000] Building R package: flexTeaching (0.1)
/mnt/packages/build /mnt
# Bootstrapping renv 0.13.2 --------------------------------------------------
* Downloading renv 0.13.2 ... OK (downloaded source)
* Installing renv 0.13.2 ... Done!
* Successfully installed and loaded renv 0.13.2.
Error: .onLoad failed in loadNamespace() for 'pillar', details:
  call: loadNamespace(x)
  error: there is no package called ‘crayon’
Execution halted
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/opt/R/4.1.0/lib/R/library’
* installing *source* package ‘flexTeaching’ ...
** using non-staged installation via StagedInstall field
** R
** inst
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package ‘flexTeaching’
* removing ‘/opt/R/4.1.0/lib/R/library/flexTeaching’
```
See https://github.com/richarddmorey/shinyapps_problem/blob/b0468cff86f105740dc4c73bccd28e8a507dc5dc/R/demo_code.R#L432

**Comment by richarddmorey** [comment]
Thanks to a suggestion from @RobinEchoAlex I tried removing all `renv` traces from the package source repository and reinstalling. Your suggestion in https://github.com/r-lib/pillar/issues/252#issuecomment-820021550 was mostly right, except it was really about the package `.Rprofile` (which had the `renv` activation code in it). Perhaps this was my misreading; I understood you meant the project `.Rprofile` getting deployed; in this case, the same file, but plays a different role in the package than in the project. It wasn't the deployment that was the problem, it was the package installation. So the package attempted loading, but then had an empty library. So this seems more of an `renv` thing. 

(re-reading the above, it seems obvious now...)

I'll close this up.

**Comment by krlmlr** [comment]
WAT.

Thanks for the heads-up.

To reiterate: if `.Rprofile` is included in an R package during `R CMD build`, we're in for big trouble? Would you mind sharing a reproducible example in the renv repo at https://github.com/rstudio/renv/?
