### ISSUE TITLE
pillar Github Actions dependency issue

### ISSUE THREAD

**Issue by shamindras** [r-lib/pillar#261]
Hi - many thanks for creating this important `pillar` library.

I'm currently collaborating (with @ricfog) on the [maars](https://github.com/shamindras/maars) `R` package. We have setup [Github Actions](https://github.com/shamindras/maars/actions) for 
our continuous integration.

One of our required dependencies is the `broom` package. In our [most recent PR](https://github.com/shamindras/maars/pull/45), we are getting the
following [CI error](https://github.com/shamindras/maars/pull/45/checks?check_run_id=1979611148) (see line `705-709` for the following message).

```
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
ERROR: lazy loading failed for package ‘broom’
* removing ‘/Users/runner/work/_temp/Library/broom’
  there is no package called ‘pillar’
```

We only started getting this CI error as of yesterday, and don't believe this error is due
to any of our recent code changes, though this may be a misunderstanding on our part.

We also tried to add `pillar` as an [explicit dependency](https://github.com/shamindras/maars/blob/iss-42-create-mlm-class/DESCRIPTION#L33) (even though we believe `broom` as a
package dependency should install this automatically). This did not fix the issue. Ideally
we would want to remove adding `pillar` as an explicit dependency, as we believe is
intended by this package.

We [also require](https://github.com/shamindras/maars/blob/main/DESCRIPTION#L22) the `tibble` package as a dependency, which we believe should also have `pillar` 
as a dependency, but only `broom` is throwing this CI error.

Could you please assist us in understanding this `pillar` or potentially `broom` and `pillar`
related issue?

Many thanks

**Comment by krlmlr** [comment]
Thanks. Version 1.5.0 of pillar is fairly new, I suspect this will auto-resolve in a few days.

**Comment by shamindras** [comment]
Thanks @krlmlr - for your very prompt and helpful response (and for your various `R` package contributions 💯 )

We will monitor this over the coming days and keep you posted.

**Comment by shamindras** [comment]
@krlmlr - **Update:** I've removed the `pillar` as a dependency. And also the [CI error](https://github.com/shamindras/maars/runs/1981677497) has resolved itself. Many thanks for 
your kind help on this.

Closing this issue.
