### ISSUE TITLE
Type headers should be computed on the entire column, not the slice of it

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pillar#266]
In clock, I have a `vec_ptype_abbr()` method for a year-month-day class that displays the number of "invalid" dates that are present in the vector. Since `type_sum()` calls `vec_ptype_abbr()` to create the column header, this nicely gets used in tibbles.

However, `tbl_format_setup.tbl()` slices the tibble down to only the rows that require formatting, which can drop the invalid dates before the header is computed. I think somehow the computation of the type headers should be lifted up out of `ctl_colonnade()` and be computed on the entire column. Or maybe `ctl_colonnade()` should pass both the sliced and unsliced data frame through, and the unsliced one can be used to compute the type headers.

``` r
library(tibble)
library(clock)

i <- year_month_day(2019, 2, 31)
x <- year_month_day(2019, 1, 1:31)

i
#> <year_month_day<day>[invalid=1][1]>
#> [1] "2019-02-31"
x[1]
#> <year_month_day<day>[1]>
#> [1] "2019-01-01"

tibble(y = c(i, x))
#> # A tibble: 32 x 1
#>    y              
#>    <ymd<day>[i=1]>
#>  1 2019-02-31     
#>  2 2019-01-01     
#>  3 2019-01-02     
#>  4 2019-01-03     
#>  5 2019-01-04     
#>  6 2019-01-05     
#>  7 2019-01-06     
#>  8 2019-01-07     
#>  9 2019-01-08     
#> 10 2019-01-09     
#> # … with 22 more rows

# should show [i=1]
tibble(y = c(x, i))
#> # A tibble: 32 x 1
#>    y         
#>    <ymd<day>>
#>  1 2019-01-01
#>  2 2019-01-02
#>  3 2019-01-03
#>  4 2019-01-04
#>  5 2019-01-05
#>  6 2019-01-06
#>  7 2019-01-07
#>  8 2019-01-08
#>  9 2019-01-09
#> 10 2019-01-10
#> # … with 22 more rows
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DavisVaughan** [comment]
Perhaps `tbl_format_setup.tbl()` could just compute the expected output `size`, rather than doing the actual slicing itself. It could pass the `size` through in `ctl_colonnade()`, all the way down to calls to `pillar()`, which could gain a new `size` or `height` argument and be responsible for doing the actual slicing, something like:

```r
pillar <- function(x, title = NULL, width = NULL, height = NULL, ...) {
  "!!!!DEBUG pillar(`v(class(x))`, `v(title)`, `v(width)`)"

  if (is.null(height)) {
    slice <- x
  } else {
    slice <- vec_slice(x, seq_len(height))
  }

  pillar_from_shaft(
    new_pillar_title(title),
    new_pillar_type(x),
    pillar_shaft(slice, ...),
    width
  )
}
```

**Comment by krlmlr** [comment]
All of this must work for lazy tables like dbplyr and multidplyr.

We could offer different code paths for in-memory and lazy tables, this looks like a deep rabbit hole.
