### ISSUE TITLE
cannot install pillar 1.5.1

### ISSUE THREAD

**Issue by djschil** [r-lib/pillar#281]
<img width="757" alt="Screen Shot 2021-03-07 at 11 16 28 AM" src="https://user-images.githubusercontent.com/54332972/110246683-92a23e80-7f36-11eb-8b77-c14d5479307c.png">

I am receiving an error when I try to install the newest version of pillar, wanted to put it on your radar.

**Comment by krlmlr** [comment]
pillar 1.5.1 is very new on CRAN, binaries are built a few days later. You should be able to do `install.packages("pillar", type = "source")`, because pillar is a source-only package.

**Comment by djschil** [comment]
@krlmlr thank you very much!

**Comment by krlmlr** [comment]
~~source-only~~ -> R-only.

**Comment by krlmlr** [comment]
Without compiled code.

**Comment by krlmlr** [comment]
Without compiled code in other languages that require specialized build tools.
