### ISSUE TITLE
FR: Move tibble:::set_dftbl_hooks() to pillar

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/pillar#288]
I have [a package](https://github.com/markfairbanks/tidytable) that currently uses `tibble::trunc_mat()` internally to print data.table's like tibbles. It's the only tibble function that I use in the package. tibble v3.1.0 deprecates `trunc_mat()`, so I started to recode the printing to use pillar. It also allows me to drop the tibble dependency.

However I noticed that when loading tibble data.frames/data.tables also print the output of `tbl_sum()` in Rmarkdown when using paged printing. Here's the example notebook:

````r
---
title: "R Notebook"
---

```{r}
data.frame(x = 1:3)
```

```{r}
# tibble:::set_dftbl_hooks()
library(tibble)
data.frame(x = 1:2)
```
````

And here's what that outputs in Rmarkdown when run in a clean session:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/28766000/111670508-25639880-87d5-11eb-8638-3085738cef14.png">

Notice how after the second code chunk the data frame printing includes a small `Description: df[, 1][2 x 1]` on the top left.

I believe I tracked this down to the internal tibble function `tibble:::set_dftbl_hooks()`. If you run that function instead of `libary(tibble)` the outcome is the same.

When I changed printing in my package to use pillar instead of `tibble::trunc_mat()` the data frame description goes away in Rmarkdown. Is it possible to move this internal function (or something similar) to pillar so that the same effect occurs without having tibble as a dependency?

**Comment by krlmlr** [comment]
Thanks. Can you please propose pull request(s) that work for you?
