### ISSUE TITLE
Option to format all numeric columns with `num`

### ISSUE THREAD

**Issue by rossellhayes** [r-lib/pillar#311]
Following from #110 

I'm not sure if this request belongs in tibble or here, but it would be helpful to have an option to convert all numeric columns to a certain `num` notation when printing. This would allow the user the option to disable scientific notation or enable one of the other notation methods on print without changing their underlying data.

As an interim solution, the user can add something like this to their `.Rprofile`, but I'm sure there could be a more efficient solution.
``` r
print.tbl_df <- function(x) {
  x <- dplyr::mutate(
    x,
    across(where(is.double), pillar::num, notation = getOption("pillar.num"))
  )
  NextMethod()
}

options("pillar.num" = "dec")
```

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by krlmlr** [comment]
Thanks! We're solving this with documentation for now. There is a stub in the "numbers" vignette, would you like to extend it with your example?

**Comment by krlmlr** [comment]
From my notes:

- Rethink tibble-local options for display: section "Rule-based formatting" in `numbers.Rmd`
    - What are the use cases, beyond databases?
    - Document pattern: helper function with `mutate(across(...))`
    - Define class that applies this?
