### ISSUE TITLE
Remove units from "Remotes" in DESCRIPTION

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#313]
pillar 1.6.0 is on CRAN now, needs units > 0.7-1 on CRAN.

CC @edzer @Enchufa2.

**Comment by krlmlr** [comment]
Are there plans to release units > 0.7-1 to CRAN in the next few weeks?

**Comment by Enchufa2** [comment]
In the next few weeks I'll address one issue and submit an update.

**Comment by Enchufa2** [comment]
On CRAN now.
