### ISSUE TITLE
`pillar_shaft.integer64()` warning with `0`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pillar#319]
``` r
pillar::pillar_shaft(bit64::as.integer64(0))
#> Warning in `*.integer64`((x[equal] - y[equal]), 2^-l2x[equal]): NAs produced by
#> integer64 overflow
#> <pillar_ornament>
#> 0
```

This comes from this line https://github.com/r-lib/pillar/blob/80fc1eae4449048fe52f6c80cd4f8c79006921d4/R/sigfig.R#L186

Which is eventually called with:

``` r
bit64::integer64(0) * Inf
#> Warning in `*.integer64`(bit64::integer64(0), Inf): NAs produced by integer64
#> overflow
#> integer64
#> [1] <NA>
```

<sup>Created on 2021-05-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by krlmlr** [comment]
The underscores are also weird in the following example:

```r
pillar::pillar_shaft(bit64::as.integer64(c(0, 1e7)))
```
