### ISSUE TITLE
Highlight significant characters for factors?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#32]
We know all levels, for `iris$Species` the characters "s", "ve" and "vi" would be highlighted.

**Comment by hadley** [comment]
Hmmm, interesting idea. I feel like this might be better enabled through a custom vector class.

**Comment by krlmlr** [comment]
What else would this class do, besides formatting and printing?

**Comment by hadley** [comment]
Nothing

**Comment by hadley** [comment]
Thinking about this more, I'm fairly certain we don't want this.

**Comment by krlmlr** [comment]
Sounds interesting. But when would you define the scales? In ggplot2, I rarely bother about scales until just before producing the final result. I wouldn't bother about them at all for intermediate tibbles.

Would you teach users to define scales just after importing, and then make sure that all operations on the data maintain the scales?

**Comment by hadley** [comment]
I think it would be more if they wanted special colouring, they'd define as needed for their table - i.e. we shouldn't do anything automatically for factors.
