### ISSUE TITLE
type_sum methods ignored for atomic vector based objects in a list column

### ISSUE THREAD

**Issue by rundel** [r-lib/pillar#321]
In a recent change to pillar atomic vector based objects are no longer using `type_sum` methods when printing in a column, see the reprex below for an example: 

```r
---
author: rundel
date: 2021-05-17
output: "reprex::reprex\\_document"
title: nerdy-ram\_reprex.R
---

``` r
---
author: rundel
date: 2021-05-17
output: "reprex::reprex\\_document"
title: choky-barb\_reprex.R
---

``` r
library(pillar)

type_sum.list_class = function(x) {
  "list obj"
}

type_sum.atomic_class = function(x) {
  "atomic obj"
}

a = structure(list(1:10), class = "list_class")
b = structure(1:10, class = "atomic_class")
x = structure(
  list(a, b),
  class = c("container", "list")
)

tibble::tibble(x = x)
#> # A tibble: 2 x 1
#>   x              
#>   <containr>     
#> 1 <list obj>     
#> 2 <atmc_cls [10]>
```

Previously the behavior was that the 2nd row would have contained `<atomic obj>`.

**Comment by krlmlr** [comment]
Thanks. It works if we override `vec_ptype_abbr()`, which is called by the default method of `type_sum()` . I don't know yet when this was introduced.

What is your use case? Do you think we need to fix this here?

``` r
library(pillar)
library(vctrs)

vec_ptype_abbr.list_class <- function(x) {
  "list obj"
}

vec_ptype_abbr.atomic_class <- function(x) {
  "atomic obj"
}

a <- structure(list(1:10), class = "list_class")
b <- structure(1:10, class = "atomic_class")
x <- structure(
  list(a, b),
  class = c("container", "list")
)

tibble::tibble(x = x)
#> # A tibble: 2 x 1
#>   x                
#>   <containr>       
#> 1 <list obj>       
#> 2 <atomic obj [10]>
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rundel** [comment]
I am using it in [parsermd](https://github.com/rundel/parsermd) when displaying the ast in a tibble format (as a column). The overall ast has a custom s3 class + list and then each node has their own S3 classes, all of these have their own specialization of `type_sum`. One of the node types was just a character vector of text lines to keep things simple, this is the failing case for me currently.

This doesn't break anything critical for me, but it introduces an undesirable display glitch (and was causing snapshot tests to fail).

**Comment by krlmlr** [comment]
Introduced in cd3b4e7520c1478d5f5eae7d45b855a76761e5ed, pillar 1.6.1 .

**Comment by krlmlr** [comment]
Making it work with `type_sum()` again requires #250, which will take quite some time because it affects downstream CRAN packages. Please implement `vec_ptype_abbr()`.
