### ISSUE TITLE
Proper use of restore and proxy

### ISSUE THREAD

**Issue by lionel-** [r-lib/pillar#322]
The vignette showcases improper use of restore and proxy:

```r
var_ <- function(x, ...) {
  out <- var(x, ...)
  vctrs::vec_restore(out, vctrs::vec_proxy(x))
}
```
Here `var_` is restoring to the proxy. The correct procedure is: Take the proxy, operate on it (e.g. with `var()`), restore to input.

I think it'd be a good idea to mention this is a rather experimental use of proxy and restore. Actually I'd prefer not showing this pattern until we've thought through numerical operations.

**Comment by krlmlr** [comment]
Should the correct use of `vec_proxy()` and `vec_restore()` be documented in `?vec_proxy` ?

**Comment by lionel-** [comment]
There is currently no documentation for creating new primitive vctrs operations since all these patterns are currently internal. Documenting this is on the long term horizon. Currently, users are expected to use the existing operations like `vec_slice()`.
