### ISSUE TITLE
Break into multiple chunks if width > getOption("width")

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#35]
as in tibble < 1.3.

**Comment by hadley** [comment]
For now, lets cut into multiple pieces at `getOption("width")`; later consider how to ensure that each column is entirely contained in one "page"

**Comment by krlmlr** [comment]
Unfortunately, this doesn't generalize well to wide characters.

I'll expand the currently implemented heuristics to multiple chunks, this shouldn't be too difficult. The only tricky case is when all columns fit with their minimum width: How to decide which column goes into which chunk? I'm positive that this can be decided by looking at the available space once, so that no backtracking is needed.
