### ISSUE TITLE
Columns of nested tibble are not shown

### ISSUE THREAD

**Issue by mgirlich** [r-lib/pillar#365]
If columns do not fit on the screen then the names are printed so that at least one knows they are there:

``` r
library(tibble)

df <- tibble(
    `1 - a long column name` = 1,
    `2 - a long column name` = 1,
    `3 - a long column name` = 1,
    `4 - a long column name` = 1,
    `5 - a long column name` = 1,
    `6 - a long column name` = 1
  )

df
#> # A tibble: 1 × 6
#>   `1 - a long column name` `2 - a long colu… `3 - a long colu… `4 - a long colu…
#>                      <dbl>             <dbl>             <dbl>             <dbl>
#> 1                        1                 1                 1                 1
#> # … with 2 more variables: 5 - a long column name <dbl>,
#> #   6 - a long column name <dbl>
```

For a nested tibble the columns not fitting on the screen are just left out without any info

```r
tibble(
  x = 1,
  y = df
)

# columns 5 and 6 of `y` are missing
#> # A tibble: 1 × 2
#>       x y$`1 - a long col… $`2 - a long col… $`3 - a long col… $`4 - a long col…
#>   <dbl>              <dbl>             <dbl>             <dbl>             <dbl>
#> 1     1                  1                 1                 1                 1
```

<sup>Created on 2021-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
Thanks. This is a known limitation. Should we print all remaining columns in the packed tibbles that are shown partially?

**Comment by mgirlich** [comment]
Yes, I think that would be great. I was very confused when I couldn't see the columns and wondered what messed up my tibble...

**Comment by krlmlr** [comment]
Similar problem: show the full column name of a column where the name is abbreviated in the header. For both issues we need somehow to communicate that truncation has happened in the pillars to the footer. Currently we only show the "extra columns" of the top-level pillars that don't fit.

This isn't entirely unsolvable, but needs the right internal data structure.

**Comment by krlmlr** [comment]
Communication isn't worth it, I'll make it clear in a different way that the data is incomplete.

**Comment by krlmlr** [comment]
Soon possible with `on_extra_cols()` .

**Comment by krlmlr** [comment]
Now:

``` r
library(tibble)

tibble(
  x = 1,
  y = tibble(z = tibble(
    `1 - a long column name` = 1,
    `2 - a long column name` = 1,
    `3 - a long column name` = 1,
    `4 - a long column name` = 1,
    `5 - a long column name` = 1,
    `6 - a long column name` = 1
  ))
)
#> # A tibble: 1 × 2
#>       x y$z$`1 - a long colu… $$`2 - a long c… $$`3 - a long c… $$`4 - a long c…
#>   <dbl>                 <dbl>            <dbl>            <dbl>            <dbl>
#> 1     1                     1                1                1                1
#> # … with 2 more variables: y$z$`5 - a long column name` <dbl>,
#> #   $$`6 - a long column name` <dbl>
```

<sup>Created on 2022-01-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Please let me know if you discover odd behavior.
