### ISSUE TITLE
Can't `pillar_shaft()` a nanotime column

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pillar#378]
``` r
library(pillar)
library(nanotime)

x <- nanotime('2011-12-05 08:30:00.000', format ="%Y-%m-%d %H:%M:%E9S", tz ="GMT")

inherits(x, "integer64")
#> [1] TRUE

pillar_shaft(x)
#> Error in abs(x): non-numeric argument to mathematical function
```

Found in https://github.com/tidyverse/dplyr/issues/6132

I'm not sure if this would immediately be "fixed" if nanotime supported `abs()`, or if more work than that is needed

**Comment by krlmlr** [comment]
Thanks. Introduced in b3aecf57422f224f293ee33b0b5413b773c9dbcf: that commit added support for bit64 columns.

Should `pillar_shaft.integer64()` forward to the default behavior if called with a subclass?

**Comment by DavisVaughan** [comment]
I think your fix makes sense.

I think in general it might make sense if `pillar_shaft()` worked sort of like `vec_ptype2()`. We don't allow inheritance in any way, so it will only recognize a method if the first class has a method, otherwise it falls back to a default operation. So this would have fallen back to a default because `nanotime` is a subclass of `integer64` and the method search would stop after failing to find a method for `nanotime`
