### ISSUE TITLE
Strange formatting of AsIs list columns

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#44]
Maybe due to `as.character.AsIs()` ?

``` r
library(magrittr)
list(a = 1:3, b = list(1, 1:2, 1:3)) %>% pillar::colonnade()
#>       a b        
#>   <int> <list>   
#> 1     1 <dbl [1]>
#> 2     2 <int [2]>
#> 3     3 <int [3]>
list(a = 1:3, b = I(list(1, 1:2, 1:3))) %>% pillar::colonnade()
#>       a b         
#>   <int> <S3: AsIs>
#> 1     1 1         
#> 2     2 1:2       
#> 3     3 1:3
```

@hadley: How do we deal with this?

Related: https://github.com/tidyverse/tibble/issues/304

**Comment by hadley** [comment]
Potentially `AsIs` could be used with anything, so I think we just need a `.AsIs()` method somewhere that just calls `NextMethod()`

**Comment by krlmlr** [comment]
Tried adding `pillar_shaft.AsIs()` to no avail -- it's handled by `pillar_shaft.default()` anyway which calls `as.character()` on the input:

``` r
as.character(I(list(1, 1:2, 1:3)))
#> [1] "1"   "1:2" "1:3"
```

Code: https://github.com/r-lib/pillar/blob/be24a37da3e36142ad52d60c3d0bad8bb5279048/R/shaft.R#L134-L138

We'd need to strip the `"AsIs"` class from the object's classes, but somehow this smells like a bad idea. Please advise.

**Comment by hadley** [comment]
You're sure this doesn't work?

```
pillar_shaft.AsIs <- function(x, ...) {
  NextMethod()
}
```

Oh, because `list` isn't in the class vector?

**Comment by krlmlr** [comment]
We could do

```r
#' @export
#' @rdname pillar_shaft
pillar_shaft.AsIs <- function(x, ...) {
  pillar_shaft.list(x, ...)
}
```

But then:

``` r
pillar::colonnade(list(a = 1:3, b = I(list(1, 1:2, 1:3, c(1:3,3)))))
#>       a b         
#>   <int> <S3: AsIs>
#> 1     1 <S3: AsIs>
#> 2     2 <S3: AsIs>
#> 3     3 <S3: AsIs>
```

Or we strip the class manually:

```r
#' @export
#' @rdname pillar_shaft
pillar_shaft.AsIs <- function(x, ...) {
  if (all(class(x) == "AsIs")) {
    class(x) <- NULL
  } else {
    class(x) <- setdiff(class(x), "AsIs")
  }
  pillar_shaft(x, ...)
}
```

That one looks better, but I'm not sure if this is a safe approach:

``` r
pillar::colonnade(list(a = 1:3, b = I(list(1, 1:2, 1:3, c(1:3,3)))))
#>       a b         
#>   <int> <S3: AsIs>
#> 1     1 <dbl [1]> 
#> 2     2 <int [2]> 
#> 3     3 <int [3]> 
#> 1     1 <dbl [4]>
```

**Comment by hadley** [comment]
An even more general approach would be to do manual switchpatch in the default method:

```R
#' @export
#' @rdname pillar_shaft
pillar_shaft.default <- function(x, ...) {
  switch(typeof(x),
    list = pillar_shaft.list(x, ...),
    numeric = pillar_shaft.numeric(x, ...),
    logical = pillar_shaft.logical(x, ...),
    pillar_shaft.character(x, ...),
  )
}
```

Then we're basically pretending that the final member of the class is always the `typeof()`.

**Comment by krlmlr** [comment]
This works if we use switchpatch also in `obj_sum.AsIs()`.

**Comment by hadley** [comment]
Oh yeah, that's a better idea

**Comment by krlmlr** [comment]
Let's keep switchpatch in mind, I haven't added it yet. Current output:

``` r
tibble::as_tibble(data.frame(a = 1:3, b = I(list(1, 1:2, 1:3))))
#> # A tibble: 3 x 2
#>       a b        
#>   <int> <I(list)>
#> 1     1 <dbl [1]>
#> 2     2 <int [2]>
#> 3     3 <int [3]>
```
