### ISSUE TITLE
pillar and github actions

### ISSUE THREAD

**Issue by ecmerkle** [r-lib/pillar#462]
Hi, there seems to be an issue with my "pkgdown" github action and the new version of pillar (1.6.5). I realize that the problem may not lie with pillar, but I'd like to check whether I am missing something obvious before I dig further. 

I am getting this error:

```
Error: Error: .onLoad failed in loadNamespace() for 'pillar', details:
  call: register()
  error: (converted from warning) Can't find generic `scale_type` in package ggplot2 to register S3 method.
```

The full logs of my github actions are here: https://github.com/ecmerkle/blavaan/actions

Thanks for any ideas!

**Comment by krlmlr** [comment]
Thanks, confirmed. I'm sure we can work around, I can release an update next week.

**Comment by krlmlr** [comment]
I tested locally. Can you please confirm if this fixes the problem in your builds?

**Comment by ecmerkle** [comment]
Thanks, I set my workflows to install pillar from github, and it now works.

**Comment by pat-s** [comment]
I also saw this causing issues in GHA builds (and local R CMD Check runs) today.
One example run from [mlr3filters here](https://github.com/mlr-org/mlr3filters/runs/4989178096?check_suite_focus=true#step:16:130).

I see from the commit log that the patch from above was done shortly after pillar 1.6.5 release - are their plans for another hotfix release or does one need to workaround manually for the the next weeks? Given that I see this issue in multiple repos, an upstream patch would be appreciated.

**Comment by krlmlr** [comment]
Aiming to release 1.6.6 on February 2.

**Comment by andrewelamb** [comment]
Hi! Would this be related to the [issue](https://github.com/CRI-iAtlas/iatlas.modules/issues/33) I'm having?

**Comment by krlmlr** [comment]
Looks like it. Releasing today or tomorrow.
