### ISSUE TITLE
`median()` does not work for `num()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/pillar#520]
``` r
median(tibble::num(1:3, notation = "eng"))
#> Error in `stop_vctrs()`:
#> ! `median.pillar_num()` not implemented.
```

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is because there is no `median()` method for `vctrs_vctr` (resp. it is defined to throw an error). Would be great to have a fallback for `median()` (and probably some other methods like `quantile()`) until this is figured out in https://github.com/r-lib/vctrs/issues/87

**Comment by krlmlr** [comment]
Thanks. I'd rather solve this by documentation for now, e.g. in https://tibble.tidyverse.org/articles/numbers.html .
