### ISSUE TITLE
new_pillar_title - format column titles conditionally (italics, red)

### ISSUE THREAD

**Issue by stemangiola** [r-lib/pillar#551]
I am trying to see how can I format columns titles, with multiple styles. I could not find many example of applications of the function `new_pillar_title`.

For example, if a tibble has 5 columns I want just one column title to be red and italic.

Thanks!

**Comment by krlmlr** [comment]
Thanks. Would you like to share an example that displays what you would like to achieve?

**Comment by krlmlr** [comment]
Thanks. I believe you need to override `ctl_new_pillar()` to achieve this. Is the documentation helpful?

https://pillar.r-lib.org/articles/extending.html#body

**Comment by krlmlr** [comment]
Happy to take feedback on the documentation.
