### ISSUE TITLE
Quotes in wrong position in character column with NAs?

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#556]
``` r
tibble::tibble(a = c(NA, "", NA))
#> # A tibble: 3 × 1
#>   a    
#>   <chr>
#> 1  <NA>
#> 2 ""   
#> 3  <NA>
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Or maybe the problem is that the `<NA>` gets a space in front of it?

**Comment by krlmlr** [comment]
This is by design, the extra space is deliberate. The `NA` aligns with the text inside the quotes:

``` r
tibble::tibble(a = c(NA, "a b", NA))
#> # A tibble: 3 × 1
#>   a    
#>   <chr>
#> 1 <NA> 
#> 2 a b  
#> 3 <NA>
```

<sup>Created on 2022-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Too confusing?

**Comment by hadley** [comment]
That example doesn't show `""` which seems like another small bug?

But yeah, I think trying to align the contents of the "" with NA is confusing.

**Comment by krlmlr** [comment]
The quotes in the example aren't necessary: even if the string contains spaces, it's unambiguous.

I went for a minimal fix for the behavior, only for very short character columns:

``` r
tibble::tibble(a = c(NA, "", NA))
#> # A tibble: 3 × 1
#>   a    
#>   <chr>
#> 1 <NA> 
#> 2 ""   
#> 3 <NA>
```

<sup>Created on 2022-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
