### ISSUE TITLE
Surv objects not printed when part of a tibble

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#558]
Only standalone.

``` r
library(survival)
library(pillar)

my_lung <- pillar:::as_tbl(lung)[2:3]
my_lung$sobj <- Surv(my_lung$time, my_lung$status)

pillar(my_lung$sobj[1:3])
#> <pillar>
#> <Surv>
#>   306 
#>   455 
#>  1010+
my_lung
#> # A data frame: 228 × 3
#>     time status sobj[,"time"] [,"status"]
#>  * <dbl>  <dbl>         <dbl>       <dbl>
#>  1   306      2           306           1
#>  2   455      2           455           1
#>  3  1010      1          1010           0
#>  4   210      2           210           1
#>  5   883      2           883           1
#>  6  1022      1          1022           0
#>  7   310      2           310           1
#>  8   361      2           361           1
#>  9   218      2           218           1
#> 10   166      2           166           1
#> # … with 218 more rows
```

<sup>Created on 2022-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
@lionel-: Any idea what could be the cause here? This also happens with the most recent compat-s3-register.

**Comment by lionel-** [comment]
I don't see `s3_register()` being involved with `Surv` pillar methods.

Inspecting the inputs to `pillar()` when the df is printed within a `browser()` session, it looks like the `Surv` object loses its attributes at some point.

I tried to understand why but the pillar internals are too complex for me.

**Comment by krlmlr** [comment]
Thanks for the hint! I forgot that Surv objects are matrices, I used to special-case for them but lack of testing made me miss the changed behavior when I broke it. The expected S3 dispatch never happened.
