### ISSUE TITLE
Control and data flow diagram not displaying properly on pkgdown website

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pillar#573]
- on pkgdown [website](https://pillar.r-lib.org/dev/articles/printing.html) (same for release and devel)

<img width="875" alt="Screenshot 2022-07-08 at 23 29 28" src="https://user-images.githubusercontent.com/11330453/178073046-38aa9336-6c54-462b-b12c-0ab60f549290.png">

- on [CRAN](https://cran.r-project.org/web/packages/pillar/vignettes/printing.html), it works as expected

<img width="1156" alt="Screenshot 2022-07-08 at 23 30 01" src="https://user-images.githubusercontent.com/11330453/178073051-5c982f42-f878-4d31-87f0-186f5ec2a4d1.png">

**Comment by krlmlr** [comment]
Introduced in 66960e33e32580962374325af87a1920aca38516, it seems that DiagrammeR got upgraded from 1.0.8 to 1.0.9.

@rich-iannone: Any idea why showing a Mermaid diagram would break for a pkgdown site with DiagrammeR 1.0.9?
