### ISSUE TITLE
0 displayed as NA

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#58]
``` r
print(tibble::tibble(x = c(0, 1e-30)), width = 20)
#> # A tibble: 2 x 1
#>                   x
#>               <dbl>
#> 1      NANANANA    
#> 2          1.00e⁻³⁰
```

**Comment by krlmlr** [comment]
Thanks, confirmed. Slightly more minimal reprex:

``` r
pillar::pillar(c(0, 1e-30), width = 20)
#>                <dbl>
#>         NANANANA    
#>             1.00e⁻³⁰
```

**Comment by krlmlr** [comment]
Zero values are shown in subtle style in both decimal and scientific views. I vaguely remember this was by design, just to confirm again:

![screenshot from 2017-10-25 21-17-07](https://user-images.githubusercontent.com/1741643/32018385-ff8c50fc-b9c9-11e7-8751-f4400afd9dc0.png)

**Comment by hadley** [comment]
Yup, LGTM
