### ISSUE TITLE
Very small numbers print as `Inf.e-324`

### ISSUE THREAD

**Issue by ccsarapas** [r-lib/pillar#615]
Reprex:
``` r
library(pillar)

pillar(4e-324)
#> <pillar>
#>     <dbl>
#> Inf.e-324
```
This looks similar to https://github.com/tidyverse/tibble/issues/377, which was previously closed at https://github.com/r-lib/pillar/commit/d3e1384f6bc75b27f94d6119020b26bc20452729.

**Comment by bbolker** [comment]
I dug in a little bit here: https://stackoverflow.com/a/74131254/190277 but didn't make it all the way to the bottom ...

**Comment by rikivillalba** [comment]
Problem appears to be the function [safe_divide_10_to <- function(x, y) {](https://github.com/r-lib/pillar/blob/746a524e9b27897b52b65b9081b716cce487ab88/R/sigfig.R#) given in R `4.940656e-324 /(10^-324)` gives Inf

**Comment by bbolker** [comment]
It's pretty funny that the source code

**Comment by krlmlr** [comment]
Thanks, good catch.

Would `10 ^ (log10(x) - y)` also work? Or is `10 ^ .` just a variant of `exp(x)` under the hood?

Is this a case of comment rot? I don't remember what happened here off the top of my head.

**Comment by rikivillalba** [comment]
This also worked for me https://stackoverflow.com/a/74132326/6912817
```
library(tibble)

print(tibble(x = c(4e-300, 4e-324, 4e324, 10, -10, 4e-350)))
#> # A tibble: 6 × 1
#>           x
#>       <dbl>
#> 1   4 e-300
#> 2 Inf.e-324
#> 3 Inf      
#> 4   1 e+  1
#> 5  -1 e+  1
#> 6   0

assignInNamespace("safe_divide_10_to", 
                  function(x,y) 10^(log10(x) - y), "pillar")

print(tibble(x = c(4e-300, 4e-324, 4e324, 10, -10, 4e-350)))
#> # A tibble: 6 × 1
#>             x
#>         <dbl>
#> 1   4   e-300
#> 2   4.94e-324
#> 3 Inf        
#> 4   1   e+  1
#> 5  -1   e+  1
#> 6   0
```
