### ISSUE TITLE
Should `*` or `i` be used for footer information?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pillar#627]
With https://github.com/r-lib/pillar/pull/617 we now use bullets for separating footer information like

<img width="739" alt="image" src="https://user-images.githubusercontent.com/19150088/219196463-ce53bbd0-7b5c-434c-8146-9f91ceae47b6.png">

Did we ever consider using `i` for this instead? In most of our error / warning messaging, we now use `i` to convey a general "info bullet" and it seems like this might fall in that category.

@lionel- do you have any thoughts about `i` vs `*` here?

**Comment by lionel-** [comment]
I think so too.

By the way, did we consider standardising the header to use the conventional angular brackets?

**Comment by krlmlr** [comment]
Like this?

```r
# A tibble: [2,196 x 11]
```

**Comment by lionel-** [comment]
Like

```r
#> <tibble [2,196 x 11]>
```

I think tibble is about the only place where we use a `#` header?

**Comment by krlmlr** [comment]
How would we print a multiline header?

**Comment by lionel-** [comment]
I think we'd use the conventional approach and wouldn't have a multiline header? More information could be displayed in bullets instead? But I don't know in what cases tibble uses multiline headers.

**Comment by krlmlr** [comment]
In subclasses of `"tbl"`:

``` r
dbplyr::memdb_frame(a = 1)
#> # Source:   table<dbplyr_001> [1 x 1]
#> # Database: sqlite 3.40.1 [:memory:]
#>       a
#>   <dbl>
#> 1     1
```

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lionel-** [comment]
Following for instance the `rlang_error` formatting, this could be:

```r
#> <table<dbplyr_001> [1 x 1]>
#> Database: sqlite 3.40.1 [:memory:]
#>       a
#>   <dbl>
#> 1     1
```

**Comment by krlmlr** [comment]
Closing, please reopen/comment if this was bad judgment.

**Comment by lionel-** [comment]
No info bullets then?

**Comment by krlmlr** [comment]
Right, we can try info bullets.
