### ISSUE TITLE
Why do `new_pillar_shaft()` and `new_pillar_shaft_simple()` default `min_width` to `width`?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pillar#646]
In bench, there is a custom expression class called `bench_expr` that displays the captured expressions

We have a `pillar_shaft()` method for this that looks like:

```r
pillar_shaft.bench_expr <- function(x, ...) {
  pillar::new_pillar_shaft_simple(format.bench_expr(x), align = "left", ...)
}
```

It seems like the way we defined this method is actually the cause of this issue
https://github.com/r-lib/bench/issues/94

i.e. if you have a very long bench expression then it won't get truncated like a normal character column would. It seems like this is because `min_width` defaults to `width`, disallowing any truncation.

It seems like I can fix it by doing this:

```r
pillar_shaft.bench_expr <- function(x, ...) {
  pillar::pillar_shaft(format.bench_expr(x), ...)
}
```

i.e. convert to character and then use the standard `pillar_shaft.character()` method.

The `pillar_shaft.character()` method respects `pillar.min_chars` through `get_pillar_option_min_chars()` so the `min_width` ends up being a good default of `3` by doing this.

I wonder if the default of `new_pillar_shaft()` and `new_pillar_shaft_simple()` should also respect this option rather than defaulting to `width`?

**Comment by DavisVaughan** [comment]
Maybe `width` is a good default for most types (because, for example, you want to see the full number with a double column), and character vectors are just a bit special?

In that case, my solution above is pretty similar to what is done for factors, so I feel pretty good about it

```r
> pillar:::pillar_shaft.factor
function (x, ...) 
{
    pillar_shaft(as.character(x), ...)
}
```

Feel free to close if you agree with my thoughts here

**Comment by krlmlr** [comment]
Thanks. The solution applied in bench looks good to me. With `rlang::expr_deparse(width = ...)`, you could perhaps truncate in a nicer way (if not done already).
