### ISSUE TITLE
Some changes make warnings in tibble

### ISSUE THREAD

**Issue by olivroy** [r-lib/pillar#665]
Changes in https://github.com/r-lib/pillar/pull/663 or #662 are likely casing  https://github.com/tidyverse/tibble/pull/1591

Maybe a simple `suppressWarnings()` will work. Will need to investigate, but wanted to log the issue as I noticed it

**Comment by krlmlr** [comment]
Thanks, good catch. Introduced in dc39397d6482eda0cc280f99dd2e19d2b5f25456.
