### ISSUE TITLE
logic of pillar.print_max pillar.print_min 

### ISSUE THREAD

**Issue by zufarmul** [r-lib/pillar#669]
logic of pillar.print_max and pillar.print_min options is strange. Quoting help:
"pillar.print_max: Maximum number of rows printed, default: 20. Set to Inf to always print all rows. 
 pillar.print_min: Number of rows printed if the table has more than print_max rows, default: 10. "

 suggestion - keep only pillar.print_max to for max number of rows displayed.

**Comment by krlmlr** [comment]
Thanks. It's been like this for a few years now. The rationale is to show "just a few more rows" if they fit. You can set both options to the same value to turn off this behavior.
