### ISSUE TITLE
NA styling

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#70]
I'm not in love with the current treatment. Did we try yellow or red foreground colour?

**Comment by krlmlr** [comment]
Please choose your preference:

![screenshot from 2018-01-10 22-14-59](https://user-images.githubusercontent.com/1741643/34795799-c4d518ce-f653-11e7-9808-df2d0bb14363.png)

Code to create the matrix:

```r
bg <- c("bgBlack", "bgBlue", "bgCyan", "bgGreen", "bgMagenta", "bgRed", "bgWhite", "bgYellow")
fg <- tolower(gsub("^bg", "", bg))

library(tidyverse)
library(crayon)

combs <- tidyr::crossing(bg, fg)

find_fun <- function(name) {
  get(name, asNamespace("crayon"), mode = "function")
}

combs %>%
  rowwise() %>% 
  mutate(na = find_fun(fg)(find_fun(bg)("NA"))) %>% 
  ungroup() %>% 
  group_by(bg) %>% 
  summarize(na = paste(na, collapse = " ")) %>% 
  ungroup() %>%
  summarize(val = paste0(format(bg), " ", na, collapse = "\n")) %>%
  pull() %>% 
  cat()
```

**Comment by hadley** [comment]
Let's try bgRed + white

**Comment by hadley** [comment]
Actually, let's just try "red" and leave the background colour alone. I think that should be sufficient contrast in most styling configs.

**Comment by krlmlr** [comment]
I do wonder why `bgWhite()` is so gray on my system...
