### ISSUE TITLE
Alignment with CJK characters

### ISSUE THREAD

**Issue by michael-dewar** [r-lib/pillar#700]
The spacing with Chinese characters is always messed up for me.  All columns to the right of the first column with Chinese won't align properly.
```
my_tbl <- tibble::tibble(
	x = c("一二三四五六七八九十", "1234567890123456", "abcdefghij"),
	y = c("一二三四五六七八九十", "1234567890123456", "abcdefghij"),
	z = c("一二三四五六七八九十", "1234567890123456", "abcdefghij"))
my_tbl
```
The problem appears to be that `pillar::get_extent()` uses `utf8::utf8_width()` which asserts that the Chinese characters are double width.  But when I print them they are actually 5/3 the width of an ASCII character.

I am using the font FiraCodeRoman-Regular in RStudio, if that makes a difference.  I have tried different fonts, but many of them seem to use 5/3 width characters.  Although I am finding it difficult to figure out how missing glyph fallback works, and maybe that is related.

**Comment by krlmlr** [comment]
Thanks. This is what I see in HTML:

``` r
writeLines(c("一二三四五六七八九十", "1234567890123456", "abcdefghij"))
#> 一二三四五六七八九十
#> 1234567890123456
#> abcdefghij
```

<sup>Created on 2024-12-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This is what I see in the RStudio IDE, using the Iosevka font:

<img width="666" alt="image" src="https://github.com/user-attachments/assets/70fbea3d-138e-4742-8326-7436253c4396">

It's going to be difficult for pillar (or any other package) to tell if the current font assumes width 5/3 or 2. We could do an option that the utf8 package picks up, but I don't have time to actively work on this. Can you find a font that uses width = 2 for Chinese characters to work around?

**Comment by krlmlr** [comment]
Browser screenshot:

![image](https://github.com/user-attachments/assets/d26495b2-59fb-41b6-9fa7-6d34bb2ee3d9)
