### ISSUE TITLE
pkgdown error with type_sum.accel

### ISSUE THREAD

**Issue by jmclawson** [r-lib/pillar#720]
The most recent release of pillar seems to coincide with errors on recent package deployments across GitHub Pages. Calling `library(dplyr)` in a pkgdown article is enough to return the following error:

```
#> Error in get(paste0(generic, ".", class), envir = get_method_env()) : 
#>   object 'type_sum.accel' not found
```

There's some good and bad here. The error doesn't stop deployment, which is good. But the error does silently print on pkgdown pages that don't hide library calls behind an `include=FALSE` chunk option in RMarkdown, and that's bad, because it can be hard to notice. Here's a sampling of some recently updated project pages that show the problem (as of 23-12-2024):

1. https://pillar.r-lib.org/articles/extending.html
2. https://docs.ropensci.org/qualR/articles/qualr.html
3. https://docs.ropensci.org/targets/reference/tar_renv.html
4. https://docs.ropensci.org/USAboundaries/articles/usaboundaries-sample-analysis.html
5. https://insightrx.github.io/PKPDsim/articles/error.html
6. https://strengejacke.github.io/ggeffects/articles/introduction_randomeffects.html
7. https://nickch-k.github.io/vtable/articles/vtablefunction.html
8. https://philippemichel.github.io/baseph/articles/my-vignette.html
9. https://takeshinishimura.github.io/fude/articles/additional.html
10. https://ahaeusser.github.io/tscv/articles/vignette_02_cross_validation.html

My best guess is that the problem was introduced by https://github.com/r-lib/pillar/commit/6f6565b5dc30769cab9cb58791e2c6ab5aa83f99 since it wasn't a problem before pillar's most recent CRAN update.

**Comment by krlmlr** [comment]
Thanks for the report! The `type_sum.accel()` method is needed only for one help page, I'm working around with registering the method only for the help page.

Trying to sneak in an update, but this may need to wait until early January.

**Comment by krlmlr** [comment]
No dice with the submission, we'll have to wait until January 7.

**Comment by jmclawson** [comment]
Understandable. Thanks for the quick work!
