### ISSUE TITLE
Column width truncation is too aggressive

### ISSUE THREAD

**Issue by hadley** [r-lib/pillar#75]
Especially given that there's no display of the full names.

**Comment by hadley** [comment]
I'd suggest at least 10 characters, maybe 15.

In a future release we should provide footnotes (or similar) so you can look up the full name

**Comment by krlmlr** [comment]
We could just use `base::abbreviate()` to keep the column names unique. For now I'll implement an option that turns off abbreviation for column names (`option(pillar.colnames = "full")` vs. `option(pillar.colnames = "trunc")`), we'll add further values later.

**Comment by hadley** [comment]
I don't think abbreviate is a good solution because you'll still need someway to map what you see back to `$` etc. I think we just need to be much less aggressive here. Increasing the minimum width constant is an easy way to fix this problem, and we can come back to better solutions in the future
