### ISSUE TITLE
Control abbreviation of column data

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#84]
This came up in tibble: https://github.com/tidyverse/tibble/issues/361#issuecomment-357314498

Sometimes truncation of character data is outright undesired, e.g. for key columns. Should we add another option here, similar to pillar.min_title_chars?

**Comment by dpeterson71** [comment]
Another case where truncation is undesirable is in list-cols containing tibbles.  Currently the output is "<tibble [..." which is rather uninformative.  Previously the dimensions of the tibble were shown  (i.e. "<tibble[2600 x 5]>") which indicated the structure of the data within.

**Comment by krlmlr** [comment]
Truncation happens only if there's not enough horizontal space. It's a choice between omitting a whole column, or show (parts of) two columns. The pillar package tends to prefer the latter.

Another option would be to abbreviate character columns in the middle and always show the last three characters. Either way, we should perhaps show at least 8 or 10 characters for character columns, and not the current default of 5 (of which one is used as continuation sign).

**Comment by kovla** [comment]
> Truncation happens only if there's not enough horizontal space. It's a choice between omitting a whole column, or show (parts of) two columns. The pillar package tends to prefer the latter.

From my perspective, it would be useful to have the option of defining which choice is more preferable. Alternatively, it may be feasible to implement two separate methods. For example, a normal print method would avoid truncation, focusing on details in the first cases it can display. This was the old behavior, and from practical standpoint it definitely provides a useful tool to quickly evaluate whether, for example, a data transformation succeeded (like a variable recoding). The alternative print method could focus on displaying as much columns as possible, thus providing a 'glance' on a tibble, with focus on overall overview. The latter might be achieved with a separate print function, I am aware that `glance()` is already being used in `broom`, but something similar maybe.

**Comment by dpeterson71** [comment]
If truncation is happening, there is already going to be information missing.   I would argue that showing incomplete columns is just as bad, if not worse, than not showing them at all.  Showing the partial data can be misleading; at least if the column is omitted the footer of the tibble tells me that there are more columns available. If I want to see their data I can either use "glimpse" or filter the tibble to focus on the columns of interest.

I think the proposed solution of allowing up to 10 characters if necessary (for *ALL* columns, not just characters) is a good one.

**Comment by randomgambit** [comment]
yet another example where default should be no truncation at all, but warned user can enable with some options

**Comment by randomgambit** [comment]
at the end of the day, this is not a big problem. You could always say: 

> This package has a great deal of power and with power comes great responsibility. This is why most of pillar's formatting choices are disabled by default. By looking carefully at the vignettes, you can understand how each formatting rule work and whether it fits your data/needs well. Happy coloring! 


something like that :)

**Comment by krlmlr** [comment]
I'm proposing https://github.com/tidyverse/tibble/pull/411 as a solution to solve all current and future column formatting desires. We should keep discussing better formatting defaults. Thanks for your feedback.

**Comment by randomgambit** [comment]
that looks great, man! thanks!

**Comment by krlmlr** [comment]
Would you like to test-drive [`char()`](https://pillar.r-lib.org/dev/reference/char.html#examples), available in pillar 1.5.1.9002, to be released as pillar 1.6.0? After release, I'll reexport this the constructor from tibble too. See https://pillar.r-lib.org/dev/articles/numbers.html for a documentation stub.

**Comment by krlmlr** [comment]
Abbreviation of list columns is handled elsewhere.
