### ISSUE TITLE
Incorrect superscript formatting for scientific notation

### ISSUE THREAD

**Issue by dpeterson71** [r-lib/pillar#90]
The pretty-printing of superscripts is not correct for numbers printed in scientific notation.  For example, the number 1.23E4 is printed as 1.23e^4 which reads as 1.23 * e^4.  It really should be 1.23 x 10^4, (which actually occupies more characters than the default print method) but at the very least the "e" should be "E" so as not to be confused with the natural exponent.

**Comment by krlmlr** [comment]
I'd argue that the lower-case `e` is easier to distinguish from numbers. R (and many other computing environments) are doing the same, albeit without superscript:

``` r
1e10
#> [1] 1e+10
```

> Created on 2018-01-16 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by dpeterson71** [comment]
There are at least two features of the R output that make it clear what is happening:

1. There is no superscript so there is no confusion about the meaning.
2. The sign immediately follows the "e" and is connected to the power whether it is positive or negative.

Another feature of base R is that it always provides at least two digits.
For comparing magnitudes of numbers it is very easy to scan a column of three characters seeing "+" or "-" signs and a number denoting magnitude.

**Comment by jonasfoe** [comment]
For me the display in the Rstudio console is very awkward with when superscript is involved.
It's kind of hard to read.
I use the menlo font on my mac which should be pretty standard.

<img width="483" alt="screen shot 2018-01-18 at 15 22 51" src="https://user-images.githubusercontent.com/9588/35102550-85a07af2-fc63-11e7-8f78-6130057d0820.png">

**Comment by pqmatagi** [comment]
I'm using the RStudio Server web client (Chrome, Mac, tibble 1.4.2) with the default UI scheme.

In addition to the annoying spacing as above that results from superscripting in the fixed width font, I get double superscripting in two-digit exponents - see attached screen clip.

![tibble](https://user-images.githubusercontent.com/7728502/35741851-d7bcea92-0806-11e8-9a77-e3332945228f.png)

So (IMHO) we get decreased readability compared to the lowest common denominator R formatting, with no saving in screen real estate, and no way to configure formatting consistent with the rest of the numbers printed in the console.

Please record one more vote for a backward compatibility option!

**Comment by alistaire47** [comment]
This printing does make it easier to understand what those numbers are, but at small font sizes or for people with bad eyesight, they're really hard to read. An option to turn them off would be nice.

**Comment by krlmlr** [comment]
Thanks for your feedback, using regular digits again.
