### ISSUE TITLE
Avoid truncating first column

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pillar#94]
if it is a character vector? Might alleviate some of the pain with ID columns.

**Comment by kovla** [comment]
Perhaps it is useful to add that IDs are not necessarily contained in the very first column. Also, they are not the only column that absolutely needs to be displayed. Perhaps an option to control truncation altogether?

**Comment by AshesITR** [comment]
Maybe do this for character columns with very limited length spectrum?
Most of my day-to-day IDs are fixed-length or have two or three different possible lengths depending on the originating system.

--> `length(unique(str_length(...))) <= 3`?

**Comment by krlmlr** [comment]
Closing in favor of #101. (The position criteria doesn't seem helpful. Would it be enough to make sure values are unique?)
