### ISSUE TITLE
Scale Numbers In Columns Equally

### ISSUE THREAD

**Issue by brodieG** [r-lib/pillar#96]
This is similar to #41, with the added constraints that the same scale should be picked for all numbers in a column.  Columns that would get this treatment are columns that have large (>= 1e5 in magnitude) or small numbers, or a range that spans more than a couple of orders of magnitude, particularly if it involves numbers that start on both sides of the decimal mark.

Here is an example from a **[twitter post](https://twitter.com/BrodieGaslam/status/954395715270250497)** from last week:

![image](https://user-images.githubusercontent.com/6105908/35392396-b7ec345a-01af-11e8-98fc-1765412d9293.png)

The idea is to make the absolute magnitude and relative magnitude of numbers graspable at a glance.  
I believe this does it with minimal clutter.  `pillar` has the added benefit of the sub-headers, so you could use:

```
 column
<dbl:K>
   1234
```

One key difference with current `pillar` concepts is that we think in terms of significance for the column as a whole, not just a single number.  So if a column contains 1e+9, and 100 as numbers, the first three digits of 100 are not actually significant.  In some cases this will be wrong, but in the bulk of use cases it should be the right way to look at it as numbers in a column are typically the result of the observation of one process with one (repeated) measurement method (with presumably fixed significance and precision for all measurements, respectively).

If you are okay with the loss of precision in the display of significant digits (i.e. we are no longer highlighting exactly 3, but between 3 and 5) then this saves the possibility of using color for other purposes.

As always I'm happy to contribute code if this is something you're interested in.

**Comment by krlmlr** [comment]
This looks like a nice idea, have you seen the units package?

**Comment by brodieG** [comment]
I have now, although that looks like it is mostly for easily converting between units, whereas all we need to do here is scale, which is much simpler (presumably scaling is also possible with units).

**Comment by krlmlr** [comment]
@edzer: Can *units* auto-format values using a "reasonable" unit, e.g. using [km] for values in the range of 1'000-100'000 m? Can we make this work with "unitless" values?

**Comment by edzer** [comment]
No, it cannot do this, and I also believe that the underlying library (udunits) cannot do this. 

For unitless values, the unit is `1`, making this e.g. `1000`, as in your example, would be quite confusing. If it is a user-defined constant, like `person`, you'd have to make a `kperson` for a factor 1000, which for many other user-defined units might not look good.

**Comment by krlmlr** [comment]
Would you like to test-drive `num()`, available in pillar 1.5.1.9002, to be released as pillar 1.6.0? After release, I'll reexport this the constructor from tibble too. See https://pillar.r-lib.org/dev/articles/numbers.html for a documentation stub.

``` r
library(pillar)
library(tibble)

col_a <- num(
  c(14578890.234, 240234.131, 40234.123),
  notation = "si", fixed_magnitude = TRUE
)

col_a
#> <tibble_num(si)|[3]>
#> [1]  14600.00k    240.00k     40.20k
tibble::tibble(col_a)
#> # A tibble: 3 x 1
#>        col_a
#>         <si>
#> 1  14600.00k
#> 2    240.00k
#> 3     40.20k
```

<sup>Created on 2021-04-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

It is a mystery to me why this is still showing three significant digits (including before the decimal dot) even if space is already spent. I'll take another look.

**Comment by brodieG** [comment]
Very nice!  I played around with it a little bit.  Maybe this is what you meant by "it is a mystery to me", but it is surprising to me that it is the least significant number that sets what gets displayed.  I would have thought it would be the most significant.  E.g., if I have a stream of cashflows that look like:

```
> cf <- c(1.1343e9, 1e3, 17.13e7)
> tibble(a=num(cf, fixed_magnitude=TRUE, sigfig=3, notation='si'))
# A tibble: 3 x 1
             a
        <si:3>
1  1130000.00k
2        1.00k
3   171000.00k
```

I would think most people (certainly I would), would expect:

```
> tibble(a=num(cf, fixed_magnitude=TRUE, sigfig=3, notation='si'))
# A tibble: 3 x 1
             a
        <si:3>
1        1130M
2           0M
3          17M
```

Or even better:

```
> tibble(a=num(cf, fixed_magnitude=TRUE, sigfig=3, notation='si'))
# A tibble: 3 x 1
          a (M)
1         1,130
2             0
3            17
```

If I'm making a billion dollars on day one, I hardly care that that I made a thousand bucks the next day.

This looks like great progress though.  Semantic display of numbers is really a part of R that needs help.

**Comment by krlmlr** [comment]
I think both options make sense. We can make it configurable by allowing e.g. `fixed_magnitude = -Inf`, `+Inf`, or any integer.

**Comment by krlmlr** [comment]
Thanks for your feedback!

**Comment by krlmlr** [comment]
With #298:

``` r
library(pillar)

col_a <- num(
  c(14578890.234, 240234.131, 40234.123),
  notation = "si", fixed_magnitude = TRUE
)

col_a
#> <tibble_num(si)|[3]>
#> [1]  14579. k    240. k     40.2k
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
