### ISSUE TITLE
bugs with non-default pillar.sigfig settings

### ISSUE THREAD

**Issue by tmelconian** [r-lib/pillar#98]
Depending on where the decimal point falls, the `pillar.sigfig` option sometimes does not work correctly when set to a non-default value.

Here is the result with the default setting, which works as expected:
```
> pillar::pillar(c(1234.56, 123.456, 12.3456, 1.23456, 0.123456))
   <dbl>
1235    
 123    
  12.3  
   1.23 
   0.123

```
(in the terminal, the 123 are highlighted, which doesn't come through the cut and paste).

So far, so good.  Now, my expectation is that if I change sigfig to 6, I will get 6 significant figures, but I don't:

```
> options(pillar.sigfig=6)
> pillar::pillar(c(1234.56, 123.456, 12.3456, 1.23456, 0.123456))
      <dbl>
1234       
 123.46    
  12.3456  
   1.23456 
   0.123456

```
The first two of these provide too few significant figures.  Additionally, the rounding on the 1234 is now wrong.

Version: pillar_1.1.0

**Comment by krlmlr** [comment]
Thanks for the concise example!

**Comment by tmelconian** [comment]
Thanks for the quick fix!
